### ISSUE TITLE
Directional Shadows do not set area correctly

### ISSUE THREAD

**Issue by mflux** [c-frame/aframe-extras#102]
For perspective shadow cameras there is shadowCameraFov. However Fov doesn't work with orthographic cameras. Since directional lights use this, you get this issue:

![screenshot 2016-10-31 16 18 40](https://cloud.githubusercontent.com/assets/1041360/19874887/bbc82eea-9f85-11e6-80f1-df76a802e2d1.png)

In order to fix this, we need to have a 'dimension' for orthographic camera frustum size exposed. For example:

    light.shadow.camera.bottom = -10;
    light.shadow.camera.left = -10;
    light.shadow.camera.top = 10;
    light.shadow.camera.right = 10;

Will display correctly:

![screenshot 2016-10-31 16 21 04](https://cloud.githubusercontent.com/assets/1041360/19874949/26858b60-9f86-11e6-807e-e0515f86bebe.png)

**Comment by donmccurdy** [comment]
Thanks for looking into this — I'll be away for the next week and can't do much meanwhile, but would be interested in adding options to support this. Or, since A-Frame scenes are consistently 1:1m scale, perhaps there are reasonable defaults to use on most scenes.

\+ @ngokevin

**Comment by donmccurdy** [comment]
@mflux does this look right? https://github.com/donmccurdy/aframe-extras/pull/110/files?w=1

and, can you share a demo (working or not) if you have one? Having some trouble on latest version of A-Frame or THREE.js and I'm not sure what's up.
