### ISSUE TITLE
init of look controls is 0,0 even if camera has a rotation value

### ISSUE THREAD

**Issue by sizvix** [c-frame/aframe-extras#104]
If my camera start with a rotation value, when I click to take the look control with mouse, the rotation move to 0,0 instead of the current rotation value ( keep the current rotation ) .
The problem is at the line 16 of aframe-extras/src/controls/mouse-controls.js

15    this.pointerLocked = false;
16    this.lookVector = new THREE.Vector2();     <-- it will set the rotation to 0,0
17    this.bindMethods();

But I don't know what values to put here for the moment , rotation="0 180 0" seems to be this.lookVector.set(2000, 0);

**Comment by donmccurdy** [comment]
A good workaround would be placing the initial rotation on a wrapper entity around the camera. Traveling now but will try to look into this in more detail later this week.
