### ISSUE TITLE
Ocean Component does not register clicks when using Cursor Component Tutorial

### ISSUE THREAD

**Issue by JGL** [c-frame/aframe-extras#105]
Following the Cursor tutorial here:
https://aframe.io/docs/0.3.0/components/cursor.html
I made a pair of components - one to change the ocean material side property to Double instead of Front sided:
https://github.com/JGL/APieceOfArtAsBigAsIndia/blob/master/src/js/material-side-modifier-ocean.js
And the other as a listener to the Cursor component:
https://github.com/JGL/APieceOfArtAsBigAsIndia/blob/master/src/js/cursor-listener.js
A demonstration of the side modifier in action can be seen here:
https://jgl.github.io/APieceOfArtAsBigAsIndia/oceanComponentWithMyComponent.html
A demonstration of the click not being triggered can be seen here:
https://jgl.github.io/APieceOfArtAsBigAsIndia/collidingWithOceanComponent.html
You can see the same Cursor Listening with the Mountain Component here:
https://jgl.github.io/APieceOfArtAsBigAsIndia/collidingWithMountainComponent.html

**Comment by donmccurdy** [comment]
Looks like the A-Frame raycaster ignores intersections with objects that don't have an entity attached:

``` js
// raycaster.js
// Only keep intersections against objects that have a reference to an entity.
intersections = intersections.filter(function hasEl (intersection) {
    return !!intersection.object.el;
});
```

In my code [here](https://github.com/donmccurdy/aframe-extras/blob/master/src/primitives/a-ocean.js#L76), I call `el.object3D.add(this.mesh);`. Presumably I should be using `el.setObject3D('mesh', this.mesh);` instead, and that would automatically set `mesh.el`.

Traveling today, and will get that patched when I'm back. Or would take a PR as well. :)
