### ISSUE TITLE
Investigate reports of compatibility issues with aframe-react

### ISSUE THREAD

**Issue by donmccurdy** [c-frame/aframe-extras#106]
Have heard from a couple of people that the combination isn't working for them. Need to investigate why that is. Couple thoughts up front:

1. Perhaps requirement of calling `registerAll()` isn't apparent.
2. Perhaps default react build puts components at the end of `<body />`, where it's too late for them to register.

**Comment by jlieb10** [comment]
@donmccurdy to add to this ticket- most of what I have tried so far from your collection has worked with `aframe-react` however I am running into an issue with the `json-loader` -- I exported a model from blender as both `.obj` and `.json` (json corresponding to THREE's json standards)- I could load it in fine as a `.obj` but not a `.json` -- console error is:

```
VM3592:1 Uncaught SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
```

Chrome 59.0.3071.115 / MacOS 10.12.6

**Comment by benjaminleonard** [comment]
Seems like you've isolated the issue now – just a heads up to say that I'm using the master branch version and the components are properly registering for me with aframe-react now that they're being registered inline.  👍

**Comment by donmccurdy** [comment]
Thanks @benjaminleonard that's good to know! Anyway yes, things will be registered inline with the next release. 😅
