### ISSUE TITLE
Issues in A-Frame 4.0

### ISSUE THREAD

**Issue by mflux** [c-frame/aframe-extras#108]
Using https://github.com/aframevr/aframe/blob/master/dist/aframe-master.js build

in A-Frame Extras this line is now deprecated

    isMobile = AFRAME.utils.isMobile();

Should be 

    isMobile = AFRAME.utils.device.isMobile();

In addition something else broke but I wasn't able to trace the callstack to somewhere useful in Extras.

![screenshot 2016-11-15 18 04 23](https://cloud.githubusercontent.com/assets/1041360/20332091/774a7cca-ab5e-11e6-8fae-5099392d501b.png)

**Comment by mflux** [comment]
The second issue with the bad stack trace seems to be an A-Frame 4.0 issue where "shadow" was not in an element's initialComponents during 

```
            initialComponents[attr.name] = utils.extendDeep(
              initialComponents[attr.name], Component.parse(attr.value || {}));
```

Perhaps A-Frame can have this fixed before release. 

Although fixing this in A-Frame still shows no shadows.

**Comment by mflux** [comment]
The first issue (device check) can be resolved via #109

**Comment by donmccurdy** [comment]
@mflux do you have a demo with shadows working correctly, prior to v0.4.0? There have always been some issues, but definitely something weird happening in v0.4.0.

``` html
<a-entity shadow-light="intensity: 0.4" position="3 10 -10" distance="50"></a-entity>
```

^With this syntax, `el.object3D` comes out undefined, so that part feels like an A-Frame bug. Guessing that's the stack trace you mention?

**Comment by donmccurdy** [comment]
Original issue is now resolved; tracking shadows in PR to aframe core: https://github.com/aframevr/aframe/pull/2350
