### ISSUE TITLE
issue with three-model loading json, but failing to parse object

### ISSUE THREAD

**Issue by facultymatt** [c-frame/aframe-extras#111]
I am trying to load 2 different Three.JS models into aframe. The models were exported from Blender using the Three.JS blander exporter. I'm following this tut: https://www.jonathan-petitcolas.com/2015/07/27/importing-blender-modelized-mesh-in-threejs.html

The model imports successfully using the json-model loader from @ngokevin found [here](https://github.com/ngokevin/respecular/blob/master/assets/components/json-model.js). Although it loads with no materials or shading - its just a solid color. 

When trying to load with aframe-extras `three-model` it fails. A few observations: 

- network request is successful with status code 200 and json is returned
- data is undefined here in [Three.js objectLoader](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ObjectLoader.js#L511)

Related to https://github.com/aframevr/aframe/issues/1342

**Comment by donmccurdy** [comment]
Do you get a different result setting `loader: json` on `three-model`? Example:

``` html
<a-entity three-model="src: url(...); loader: json"></a-entity>
```

This may behave more similarly to `json-model`.

**Comment by donmccurdy** [comment]
As far as the solid colors, I'd check the JS console for any errors — perhaps crossOrigin issues on the image(s)?

**Comment by facultymatt** [comment]
@donmccurdy cross origin is not an issue - I'm not getting any console errors for that. 

I do see that `json` loader works better but `materials` is not defined [here](https://github.com/donmccurdy/aframe-extras/blob/master/src/loaders/three-model.js#L59).

Wrapping the materials loop in a `if (materials)` prevents the error but it breaks other things. 

I suspect I'm exporting incorrectly? Is there an option to include materials in the export process which I'm missing???

**Comment by donmccurdy** [comment]
Hm, sorry that's not working. Are you able to share the model, by any chance?

[There may be some underlying issues](https://github.com/mrdoob/three.js/issues?utf8=%E2%9C%93&q=blender%20export%20material) in the exporter or the THREE.js loader, as well. Unfortunately I'm no expert on Blender or the export process.

**Comment by donmccurdy** [comment]
Sorry, I don't think I can help more here without seeing a model, but it sounds like this may be an incompatibility in either the exporter or THREE.JSONLoader, or your materials are not compatible with three.js. Might also want to try dragging the model into the [three.js editor](https://threejs.org/editor/).

If there is a bug with the exporter or THREE.JSONLoader, those can be reported [here](https://github.com/mrdoob/three.js/issues/new).
