### ISSUE TITLE
CORS issue on three-model 

### ISSUE THREAD

**Issue by msj121** [c-frame/aframe-extras#112]
I definitely don't have an issue for images/video now that I have moved over to S3 Amazon, but when I load the model, the texture that is referenced by the model does exist relatively, but has a CORS issue.

My guess is that there is no crossoriging='' being set on the materials/textures when they are being loaded. Is anyone else experiencing this issue?

I got a random model off the web thats ThreeJS to demo the issue:

`<a-entity three-model="loader: json;animation:__auto__;src:url(http://s3.amazonaws.com/liveride/Reum54kBTK4hYd82y/miku.min.json);"></a-entity>`

> DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at http://s3.amazonaws.com/liveride/Reum54kBTK4hYd82y/miku.png may not be loaded.(…)

**Comment by donmccurdy** [comment]
Added `crossorigin` option to fix this:

``` html
<a-entity three-model="loader: json;
          animation: __auto__;
          src: url(http://s3.amazonaws.com/liveride/Reum54kBTK4hYd82y/miku.min.json);
          crossorigin: anonymous;">
</a-entity>
```

**Comment by msj121** [comment]
Awesome! Works perfectly!!!
