### ISSUE TITLE
shadow on plane

### ISSUE THREAD

**Issue by dirkk0** [c-frame/aframe-extras#113]
Hi Don, thx for your great work!

I am aware that shadows are an experimental feature but I created this pen to have a simple example nevertheless:
http://codepen.io/dirkk0/pen/qqRXwX

I noticed the issue that if you make a larger plane (8,8 instead of 4,4) the shadow of the sphere is cut as if it were clipped against the 4,4-plane:
http://codepen.io/dirkk0/pen/ENZwam

I wonder why that is?

Best,
  Dirk

**Comment by donmccurdy** [comment]
Should be fixed with aframe-extras#v2.7.3, although I'm not sure the default settings are right for everything. When making a directional `shadow-light`, there are parameters to configure the camera used while projecting shadows. These are default values:

``` html
<a-entity position="-15 25 0"
          shadow-light="type:directional;
                        shadowCameraTop: 10;
                        shadowCameraBottom: -10;
                        shadowCameraLeft: -10;
                        shadowCameraRight: 10;">
</a-entity>
```

**Comment by dirkk0** [comment]
ok, these are my standard settings for what it's worth. Couldn't tell you why (mostly ripped from mrdoob) but plays nicely with my experiments.

```                // via http://pages.cs.wisc.edu/~lizy/mrdoob-three.js-ef5f05d/examples/webgl_lights_hemisphere.html
                myInstance.scene.fog = new THREE.Fog( 0xffffff, 1, 5000 );
                // LIGHTS
                var hemiLight = new THREE.HemisphereLight( 0xffffff, 0xffffff, 0.6 );
                hemiLight.color.setHSL( 0.6, 1, 0.6 );
                hemiLight.groundColor.setHSL( 0.095, 1, 0.75 );
                hemiLight.position.set( 0, 500, 0 );
                hemiLight.name = "hemilight";
                myInstance.scene.add( hemiLight );
                // var ambLight = new THREE.AmbientLight( 0x808080 );
                // myInstance.scene.add( ambLight );
                var dirLight = new THREE.DirectionalLight( 0xffffff, 1 );
                // dirLight.color.setHSV( 0.1, 0.1, 1 );
                dirLight.position.set(  10, 10, 10 );
                dirLight.position.multiplyScalar( 50);
                dirLight.name = "dirlight";
                dirLight.castShadow = true;
                dirLight.shadow.mapSize.height = dirLight.shadow.mapSize.width = 1024*2;
                var d = 300;
                dirLight.shadow.camera.left = -d;
                dirLight.shadow.camera.right = d;
                dirLight.shadow.camera.top = d;
                dirLight.shadow.camera.bottom = -d;
                // dirLight.shadow.camera.updateProjectionMatrix();
                dirLight.shadow.camera.far = 3500;
                dirLight.shadow.bias = -0.0001;
                // dirLight.shadow.darkness = 0.35;
                myInstance.scene.add( dirLight );
```

**Comment by donmccurdy** [comment]
thanks @dirkk0! I guess `d` would vary with the size of the scene or something? That's helpful to see.

**Comment by dirkk0** [comment]
I didn't test it properly yet, but yes, d is related to the size of the scene. The code above is from the follow-up of this example:
https://github.com/dirkk0/threejs_daynight.
The shadow.x code changed in recent threejs versions, though, so I should update this repo.
