### ISSUE TITLE
Is there any plan to support daydream view controller input?

### ISSUE THREAD

**Issue by jpatrickpark** [c-frame/aframe-extras#114]
So that as long as you connect the controller via bluetooth you can use controller in web browsers without having to install daydream application? Is this possible?

**Comment by donmccurdy** [comment]
I hope so! The main question is whether Daydream controller will be available to browsers through the [HTML5 Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API). Without that, there's nothing I can do. Unfortunately I don't have a Daydream device to test this (and it could be a "not yet but later" thing, too).
