### ISSUE TITLE
Grab trouble

### ISSUE THREAD

**Issue by sirkitree** [c-frame/aframe-extras#115]
Hi, I'm trying to use grab with aframe 0.4.0. Here's how I've set this up - is there anything I'm missing?

**index.js** (registration)
```js
require('../vendor/aframe.min.js'); // 0.4.0 from master
require('aframe-teleport-controls');
var physics = require('aframe-physics-system');
physics.registerAll();
var extras = require('aframe-extras');
AFRAME.registerComponent('grab', extras.misc['grab']);

// Patched sphere module to fix deprecation warning (from https://github.com/thenayr/kuberentes-vr-frontend)
var sphereCollider = require('../vendor/sphere-collider-patched');
AFRAME.registerComponent('sphere-collider', sphereCollider);
```

**html** (hand controller components)
```html
          <a-entity static-body="shape: sphere; sphereRadius: 0.02"
                    vive-controls="hand: left"
                    class="controllers"
                    sphere-collider="objects: .hex-sphere-wrapper"
                    teleport-controls
                    grab></a-entity>
          <a-entity static-body="shape: sphere; sphereRadius: 0.02"
                    vive-controls="hand: right"
                    class="controllers"
                    sphere-collider="objects: .hex-sphere-wrapper"
                    teleport-controls
                    grab></a-entity>
```

It seems from examples here and within https://github.com/thenayr/kuberentes-vr-frontend that you should just be able to register the component and include the attribute on your vive-controls and that should allow you to grab objects, correct? Is there anything else I'm missing?

My scene currently collides with the physics-system addition correctly, allowing my controllers to push the objects around as expected, but can't seem to grab. Any insights would be greatly appreciated.

**Comment by donmccurdy** [comment]
This looks more or less right to me, but could you set up a running demo someplace? A couple ideas:

1. the stable release of aframe-physics-system doesn't support 0.4.0 yet (i think master branch does, but haven't tested thoroughly yet).
2. What is "hex-sphere-wrapper"? If that wrapper is *around* the object with a `dynamic-body`, and doesn't have a `dynamic-body` itself, that may be a problem.
3. aframe master may just have new changes since the last time I checked.. planning to test things out more carefully when is 0.4.0 officially done/released.

**Comment by donmccurdy** [comment]
Also, if the hex-sphere-wrappers are added dynamically, you'd need to update `sphere-collider` to refresh its object cache.

**Comment by sirkitree** [comment]
Thanks!

Here's a sample of what I'm doing: http://codepen.io/sirkitree/pen/BQJzEG?editors=1000#0

If you run this in the latest Chromium with a Vive, you'll see that the physics are working pretty well. It's just the grabbing that isn't happening, even if I remove the sphere-collider attribute and re-apply it (did this in a console)

```
                        [].slice.call(document.querySelectorAll('.controllers')).forEach((el) => el.removeAttribute('sphere-collider'));
                        [].slice.call(document.querySelectorAll('.controllers')).forEach((el) => el.setAttribute('sphere-collider', 'objects: .hex-sphere-wrapper'));
```

**Comment by sebkasanzew** [comment]
I'm having the same problem (also on Chromium with Vive).
I tried it with aframe version 0.4.0 and aframe-extras@3.1.0 and also aframe@0.3.2 and aframe-extras@2.6.1.
In both cases the colliding physics are working, but I cannot grab the objects.

**Comment by donmccurdy** [comment]
I should also point out there is no version 0.4.0 yet, just the unstable master branch. When it is released I will bump code here to be compatible, in the meantime it's "best effort".

**Comment by donmccurdy** [comment]
I think `sphere-collider` + `grab` from aframe-extras should be working normally in the latest version. By default the `sphere-collider` will also detect when new children are added to the scene now.
