### ISSUE TITLE
renderSingleSided and renderReverseSided properties for shadow (feature request)

### ISSUE THREAD

**Issue by takahirox** [c-frame/aframe-extras#117]
I want `renderSingleSided` and `renderReverseSided` passed to `renderer.shadowMap.renderSingleSided` and `renderer.shadowMap.renderReverseSided` respectively.

Some models I'm working with need them `false`.

First I tried to add them in `shadow-light` but
a conflict will happen if two or more `shadow-light` exist and set different values.

Any ideas?

**Comment by donmccurdy** [comment]
+1 for supporting this. I like @ngokevin's suggested syntax [from this comment](https://github.com/aframevr/aframe/issues/651#issuecomment-239231394), which could support something like:

```
<a-scene shadow="type: soft;
                 renderReverseSided: false;">
  <a-box shadow="cast: true;
                 receive: false" />
  <a-light light-shadow />
</a-scene>
```

**Comment by donmccurdy** [comment]
Included in PR to aframe core.
