### ISSUE TITLE
teleport-controls does not respect y-height when `mode` is set to `teleport`

### ISSUE THREAD

**Issue by UXVirtual** [c-frame/aframe-extras#118]
I've found an issue with `checkpoint-controls` where the y-height of the user is not respected when the `mode` is set to `teleport`. The following adjustment to line 61 of `checkpoint-controls.js` seems to fix this:

```
if (this.data.mode === 'animate') {
      targetPosition.y = position.y;
}
```

**Comment by donmccurdy** [comment]
Thanks for filing the issue / sorry for the delay. I'd like to get this fixed but haven't had the chance yet. I think the solution doesn't need to be specific to `animate` mode, but regardless you're right that Y-height should be included.

**Comment by donmccurdy** [comment]
Fixed for both modes, but note that you will need a bit of nesting to make this work correctly:

```html
<a-entity universal-controls="movementControls: checkpoint"
          checkpoint-controls="mode: animate">
  <a-entity camera="userHeight: 1.6">
    <a-entity cursor="maxDistance: 30"
              position="0 0 -1"
              geometry="primitive: ring; radiusInner: 0.02; radiusOuter: 0.03;"
              material="color: #CCC; shader: flat;">
    </a-entity>
  </a-entity>
</a-entity>
```
