### ISSUE TITLE
Loader syntax

### ISSUE THREAD

**Issue by dirkk0** [c-frame/aframe-extras#125]
Hi Don,

  I am trying to update the FAQ section over at the Aframe github and for that I created minimal examples of loaders which I intend to add soon.

I get a somewhat inconsistent behaviour with the json loader, and wonder if you can point out what I am doing wrong.

I created these two examples, one of them working, the other not so much:
http://curious-electric.com/aframe/json/doesnotwork.html
http://curious-electric.com/aframe/json/works.html

Any ideas?

Thanks,
  Dirk

**Comment by donmccurdy** [comment]
Unlike `collada-model`, `json-model` has multiple properties. So these will work:

- `json-model="src: #object"`
- `json-model="src: url(...)"`

But these will not:

- `json-model="#object"`
- `json-model="url(...)"`

^The latter is only possible for single-property components. I'm undecided about whether all loaders can/should be single-property.

**Comment by dirkk0** [comment]
Got it, thank you!
