### ISSUE TITLE
sphere-collider removes collided state after 1 tick

### ISSUE THREAD

**Issue by wmurphyrd** [c-frame/aframe-extras#130]
Starting with c00c357, collided entities are getting the `collided` state for 1 tick when a collision begins, but have it removed on the next tick even if nothing moves. I think it's caused by [this line](https://github.com/donmccurdy/aframe-extras/commit/eb209009fdfbc39eec7ed1c18e449f84757d70c4?diff=split#diff-1e24ef210280a82fe1a31cf8c71e163eR64), as `intersect` is now creating new objects as opposed to storing a reference [here](https://github.com/donmccurdy/aframe-extras/commit/eb209009fdfbc39eec7ed1c18e449f84757d70c4?diff=split#diff-1e24ef210280a82fe1a31cf8c71e163eR86). 

I could work on a PR with a unit test and fix for this, but I'm not sure about performance impact. Would `collisions.some(function (newCollision) { collision.el === newCollision.el })` be acceptable?

**Comment by donmccurdy** [comment]
Ah, yeah I think you're right. I won't be able to work on this until the weekend but that proposed change looks fine. Can tune the performance later if it's an issue.
