### ISSUE TITLE
Should animation-mixer support playing all animations at once?

### ISSUE THREAD

**Issue by ngokevin** [c-frame/aframe-extras#137]
Right now I'm using a simple component based on the mixer at https://aframe-school-gltf-model.glitch.me/solution.html:

```js
/* global AFRAME, THREE */

/**
 * Player for animation clips. Intended to be compatible with any model format that supports
 * skeletal or morph animations.
 */
AFRAME.registerComponent('play-all-model-animations', {
  init: function () {
    this.model = null;
    this.mixer = null;

    var model = this.el.getObject3D('mesh');
    if (model) {
      this.load(model);
    } else {
      this.el.addEventListener('model-loaded', function(e) {
        this.load(e.detail.model);
      }.bind(this));
    }
  },

  load: function (model) {
    this.model = model;
    this.mixer = new THREE.AnimationMixer(model);
    this.model.animations.forEach(animation => {
      this.mixer.clipAction(animation, model).play();
    });
  },

  tick: function (t, dt) {
    if (this.mixer && !isNaN(dt)) {
      this.mixer.update(dt / 1000);
    }
  }
});
```

Would it make sense to support playing all clips at once (e.g., `playAllClips` property)? Also, should animation mixer be a `multiple` component to play multiple clips at once?

**Comment by donmccurdy** [comment]
I think we need something like that, yes. Ideas (including the two you suggested) —

1. Add `playAllClips` property, overriding `clip`.
2. Support multiple `animation-mixer` components.
3. Support some sort of wildcard syntax, e.g. `animation-mixer="clips: *"` or `animation-mixer="clips: run_*"` .

I had been leaning toward (3). But (2) is interesting as well; maybe both?

**Comment by ngokevin** [comment]
3) is a great idea

Take an array or wildcard string

**Comment by donmccurdy** [comment]
Array might make sense too, or is that the case where you might want multiple `animation-mixer` components? Because there's a `duration` property too, and then options for crossfading animations that I haven't even tried out yet. Maybe we'll see how this goes in the real world and make adjustments. 😬

Should I publish `animation-mixer` to the registry? Or would it make more sense in core?
