### ISSUE TITLE
how to enable cursor display with universal controls

### ISSUE THREAD

**Issue by macheeto** [c-frame/aframe-extras#142]
Hello,
Thank you for putting the extras together, they help a lot with developing in AFrame for desktop.
My question is simple, I'd like to find out how to enable the cursor icon (a visible ring) when using universal controls. It helps to see the cursor when interacting with 3d objects.
My test example is as follows:
a-scene
	a-entity camera="userHeight: 1.6" universal-controls position="0 1 4" /a-entity
	a-sky color="green" /a-sky
	a-box position="0 3.5 -2" rotation="30 30 0" color="skyblue"
		event-set__enter="_event: mouseenter; material.color: yellowgreen; scale: 3 1 1"
		event-set__leave="_event: mouseleave; material.color: skyblue; scale: 1 1 1"
		a-animation attribute="rotation" begin="click" dur="500" fill="backwards" to="30 30 45" /a-animation
	/a-box
/a-scene

How can I configure the camera element to display the cursor? Thanks a lot!

**Comment by donmccurdy** [comment]
Hi @macheeto – the cursor works very similarly to how it does with the normal A-Frame controls. It needs to be nested as a child of your camera, so that it will rotate as the user looks around.

```
      <a-entity camera="userHeight: 1.6" universal-controls>
        <a-entity cursor
                  position="0 0 -1"
                  geometry="primitive: circle; radius: 0.01; segments: 4;"
                  material="color: #FF4444; shader: flat"></a-entity>
      </a-entity>
```

There is more documentation on the cursor in general [here](https://aframe.io/docs/0.5.0/components/cursor.html).
