### ISSUE TITLE
Investigate loading animations from separate files

### ISSUE THREAD

**Issue by donmccurdy** [c-frame/aframe-extras#147]
Useful for mixamo, which exports each animation to its own FBX file.

If possible, it would be nice to support something like this:

```html
<a-entity gltf-model="base-model.gltf;"
          animation-mixer="clip: run;"
          fbx-animation__1="run.fbx"
          fbx-animation__2="jump.fbx"></a-entity>
```

**Threads that could use answering**:

- https://community.mixamo.com/hc/en-us/community/posts/210029137-Mixamo-to-ThreeJS
- https://groups.google.com/forum/#!topic/threejs/um0yq7mAOUA

**Comment by donmccurdy** [comment]
Spent some time trying this. Was able to load the animation files from Mixamo individually, but loading the rigged mesh itself, coming from Mixamo, has been a headache. Depending on the export method the skeleton will be messed up, or the UVs are bad, or something else goes wrong.

Anyway this doesn't work yet, but the animation clips themselves do load correctly:

```html
<a-entity gltf-model="src: url(../assets/mixamo/lowpoly/character.gltf);"
          animation-mixer="clip: walk;
                           crossFadeDuration: 1;
                           useSkinnedMeshRoot: true;"
          fbx-animation__1="name: walk;
                            src: url(../assets/mixamo/lowpoly/walking_inPlace.fbx);"
          fbx-animation__2="name: idle;
                            src: url(../assets/mixamo/lowpoly/idle.fbx);"
          fbx-animation__3="name: right_turn;
                            src: url(../assets/mixamo/lowpoly/right_turn_90.fbx);"
          fbx-animation__4="name: left_turn;
                            src: url(../assets/mixamo/lowpoly/left_turn_90.fbx);"
          scale="0.1 0.1 0.1">
</a-entity>
```

Some code checked in on [feat-mixamo branch](https://github.com/donmccurdy/aframe-extras/tree/feat-mixamo).

**Comment by samuelcardillo** [comment]
I made a video to explain how to merge all the Mixamo animations in one Three.JS-compatible file and use it in A-Frame:
https://www.youtube.com/watch?v=hheYLOworF4

Its a bit painful to do so a solution where you can import the animations from the different files (as your example) would be way easier!

**Comment by donmccurdy** [comment]
Closing this issue — rather than trying to deal with FBX, which seems like it would be a never-ending thing, i'm hoping we can get somewhere on this with glTF... the [blender exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter/) seems to handle animation reasonably well now, and should support multiple actions soon. Perhaps Sketchfab will add animation to their animation export as well.
