### ISSUE TITLE
keyboard entry into text input (of w a s d) causes unwanted movement of camera

### ISSUE THREAD

**Issue by rob-lindman** [c-frame/aframe-extras#150]
my page, with a desktop 'use-case', has a text entry field for communication, in addition to the aframe scene. 

using universal-controls on the camera, pressing the w a s d keys anywhere in the page (such as the chat window).

is it possible to accept this input and move the camera only if the scene has focus? or perhaps to suspend the keyboard processing when textareas or other fields have focus?

**Comment by donmccurdy** [comment]
The easiest thing would be to disable the controls while the input is focused. Something like:

```js
var controlEl = document.querySelector('[keyboard-controls]');
inputEl.addEventListener('focus', function () {
  controlEl.setAttribute('keyboard-controls', {enabled: false});
});
inputEl.addEventListener('blur', function () {
  controlEl.setAttribute('keyboard-controls', {enabled: true});
});
```

**Comment by donmccurdy** [comment]
Could also change `keyboard-controls` to automatically ignore events if [`AFRAME.utils.shouldCaptureKeyEvent(event)`](https://github.com/aframevr/aframe/blob/2600f363d67e2bb82b8f7472a955fc0c09dddef5/src/utils//index.js#L193-L196) is `false`. I'd accept a PR if you have time to try that. :)

**Comment by rob-lindman** [comment]
I am very new to this so I am not really sure where I would put this ignore code. I have the 'qz-keyboard' component working basically based on what you provided. If this call should be put somewhere in that code, I just need to know 'where'. Also not sure what a PR is.

**Comment by rob-lindman** [comment]
I was able to get the controlEl method you first described to work properly. This will get tedious if I have to put it in for each and every element. So I am interested and curious as to how to resolve the issue the second way you described, so I can wrap the general keyboard functions into the component, and then pass it back to you for whatever you would like to do with it.

**Comment by donmccurdy** [comment]
Went ahead and did that second change (https://github.com/donmccurdy/aframe-extras/commit/11f92ae8da1708e56a0e602cff051784d28be310); in aframe-extras 3.8.2 the `keyboard-controls` component should ignore events while you are using inputs.
