### ISSUE TITLE
hex grid

### ISSUE THREAD

**Issue by morandd** [c-frame/aframe-extras#152]
Saw some commit notes here about hex grid; just wanted to point to 

[aframe-hexgraph-hexmap](http://github.com/morandd/aframe-hexgraph-hexmap)

if you hadn't seen it before

**Comment by donmccurdy** [comment]
I saw it right after I created my own 😆

yours seems to have more features; mine only loads from a JSON file and grabs a material from the `material` component. 

The palette feature looks really nice; how does that work? Does each hex tile get a random color selected from the palette?

**Comment by morandd** [comment]
Yes the two are fairly different.

- Mine reads input data from a PNG/image file and bins the data into a hex grid. There's only basic JSON input, in vector/matrix form, but not as x/y coords.
- I use d3.colorize() functions to map bin value to a palette. The palettes can be provided as an array of colors, or there are some built-in ones as well. It's easy to see the logic in the .js file. A few more Standard material properties are exposed as component attributes.
- Mine builds a BufferGeometry. The default vonGrid engine generates a Geometry for each hex tile. 
- I'm considering dropping the vonGrid dependnecy, since at this point fairly little of that code is used.

Note that vonGrid has a dev branch that may have significant refactoring. The creator mentioned this in one Issue discussion.

I build it for data viz, hence the hex binning and palette features. I was totally inspired by the very cool deck.gl hex layer.

**Comment by morandd** [comment]
got it looking pretty decent with shader hacking :)

I draw the palette into a 1xN image then apply the coloring, based on height, in the shader. So as they animate they change color.

http://folk.ntnu.no/daniemor/vr/hexmap/
