### ISSUE TITLE
[controls] Vive controls forward/backward movement bug?

### ISSUE THREAD

**Issue by evhan55** [c-frame/aframe-extras#157]
Hi!

I am testing universal-controls here at this Networked A-Frame page:
https://sugar-sponge.glitch.me

wasd and HTC Vive and Daydream controls all work, thank you!

However, the HTC Vive controller forward and backward motion seems reversed:
- pushing forward on the Vive controller (towards top of controller) moves camera back
- pushing backward on the Vive controller (towards bottom of controller) moves camera forward

The similar forward/backward motions on the Daydream trackpad do the opposite (and more-seemingly correct) thing for me.

Thank you!
Evelyn

**Comment by sidequestlegend** [comment]
I was able to replicate this using an oculus on steam where the controls appeared to be vive controls.

**Comment by vincentfretin** [comment]
This is a really old issue. Please test again with aframe master and latest aframe-extras master and create a new issue if you still have an issue. Closing it.
