### ISSUE TITLE
Replace kinematic-body with simple non-physics-based navigation.

### ISSUE THREAD

**Issue by donmccurdy** [c-frame/aframe-extras#161]
Requires removing support for platformer examples (monument, platforms, playground).

Instead, push teleport mechanics and possible touch-to-move, and try to make it easy-as-possible to get started simply. Ideally, the same map could be used for NPC navigation, without needing to duplicate work.

See also: https://github.com/lo-th/Dedal.lab/

**Comment by donmccurdy** [comment]
@scottmsinger were you looking at publishing something along these lines? I've been wanting to drop my physics-based player navigation, and either (a) replacing it, or (b) direct folks to better options.

**Comment by scottmsinger** [comment]
It's probably similar - though mine is using a raycast in the direction of travel just in front of the constrained object and checking if it hits the constraint mesh. I'm sure there's a better way of doing this that's a more general geometric solution. Unity has this functionality in NavMesh. Maya and other animation packages have fast ways of constraining the motion of a transform to the surface of a mesh.
What would nice about a true mesh constraint is that you could use the information about the surface point to inform the constrained object - orient to normal, look up vertical offset or speed from a map or vertex attribute, etc.
Ideally someone with better computational geometry chops would write the component as a general purpose surface analysis component that plugs into a general purpose constraint component. It's the kind of thing I've implemented in Maya and Houdini, but they have very robust libraries for accessing geometry.

**Comment by donmccurdy** [comment]
Good to know, thanks! So in Unity, the NavMesh would be created by analyzing the geometry automatically plus some user input?
