### ISSUE TITLE
Grab obj models

### ISSUE THREAD

**Issue by evhan55** [c-frame/aframe-extras#164]
Hello!

I am trying a modified version of the vive example and added a fourth object: a custom obj.
It shows up with a box for a bounding box, and I can hit it with my controller colliders, but I can't grab it, even though it has the same 'cube' class as the cubes do.

Would be happy to post sample code.

Thank you!

**Comment by donmccurdy** [comment]
The problem is that the custom OBJ has more than one mesh embedded in it, and the `sphere-collider` component doesn't look at all the nested stuff to compute a bounding sphere.

So, https://github.com/donmccurdy/aframe-extras/issues/156 is the underlying issue — will be able to fix that for sure, but I haven't been able to get to it yet. :)

**Comment by evhan55** [comment]
Ah ok thanks! I guess I was expecting it to collide/grab with the red bounding box and not the custom OBJ geometry, which would be fine for what I am trying to test.  Thanks anyway!

Do you happen to have any suggestions of other a-frame components to look at that allow vive-grabbing of custom objs?

Thanks again!

**Comment by donmccurdy** [comment]
The versions of `grab` and `aabb-collider` components used in the aframe tracked controls example (https://github.com/aframevr/aframe/tree/master/examples/showcase/tracked-controls) should work with custom OBJs. But you'll probably lose physics in that case.

Hopefully/maybe I should be able to look at this more this weekend 🙂

**Comment by evhan55** [comment]
Okay thanks very much! I will check that example out. But yeah, the physics is definitely the interesting aspect for me here! The vive example here in `aframe-extras` is really great, what is implemented so far!

Just to confirm, it does seem like my custom OBJ here gets a red-mesh bounding box, and I can collide with it, just not grab it (because of the issue you mention), does that sound right to you?

**Comment by donmccurdy** [comment]
> Just to confirm, it does seem like my custom OBJ here gets a red-mesh bounding box, and I can collide with it, just not grab it (because of the issue you mention), does that sound right to you?

Exactly right — grabbing doesn't use physics for collision detection (if it did, your hand would have to go inside the object, which doesn't work if you want to also push the object around), and the non-physics collision detection it uses instead has a bug.

**Comment by evhan55** [comment]
Excellent, thank you! Makes total sense to me now! So interesting! Ok I will sit tight..

**Comment by evhan55** [comment]
I was able to approximate my model with combined a-frame primitives, and the grabbing works there for the most part! :smile:

on the left, obj that is not grab-able --> on the right, a-frame model that is grab-able

<img width="588" alt="screen shot 2017-07-27 at 2 20 48 pm" src="https://user-images.githubusercontent.com/699840/28685799-f3428ff8-72d6-11e7-98b2-815937b67829.png">

**Comment by donmccurdy** [comment]
Should be fixed, i think!

**Comment by evhan55** [comment]
Oooh yay!  Thank you so much! This is great!
![ice cream grab](https://user-images.githubusercontent.com/699840/28759686-33cb49ae-756e-11e7-8771-bc1820d71f86.gif)
