### ISSUE TITLE
Support overriding material on gltf models?

### ISSUE THREAD

**Issue by twastvedt** [c-frame/aframe-extras#167]
I would like to be able to load an object from a gltf file and apply a material created within A-Frame with custom shaders. A-Frame supports this on OBJ (not COLLADA). Is this planned (or current, and I'm missing something)? I've tried this with gltf-model-next without success but have it working with obj. Thanks!

**Comment by donmccurdy** [comment]
The problem is, A-Frame's `material` component can add materials to things that don't have them, but it can't override properties on an existing material. It happens to work with OBJ only if you don't have an MTL file (which would provide a material itself, breaking the `material` component). 

glTF files always have materials, so unfortunately there's no way for me to make it compatible with `material` on this end.

What you can do is write a short component that overrides material values the way you want. Especially for custom shaders, this is the way to go. Here's [an example](https://glitch.com/edit/#!/aframe-displacement-shader?path=client/index.js:1:0).

**Comment by twastvedt** [comment]
Got it. Thanks for the explanation! Your link is exactly what I'm looking for. Thanks!

**Comment by twastvedt** [comment]
Hmm. Sorry to resurrect, but I tried that and the material isn't taking. I also remixed the example you sent, [here](https://gltf2-shader-test.glitch.me), to use a gltf model instead of the built-in sphere, with the same results. If I query `document.getElementById('duck').getObject3D('mesh').material.fragmentShader` in the terminal, I get the correct shader, so I'm not sure why it's not using the assigned material. Am I still missing something? Thanks!

**Comment by donmccurdy** [comment]
With models that aren't just primitive shapes, there can be any number of wrapping THREE.Object3D or THREE.Group objects as parents of the actual Mesh(es). Assigning a material to a parent won't work, so instead in the `update` method you will need:

```js
const object = this.el.getObject3D('mesh');
const material = this.material;
if (object) {
  object.traverse(function (node) {
    if (node.isMesh) node.material = material;
  });
}
```

**Comment by twastvedt** [comment]
Right, OK. Should have thought of that. It's working now, thanks!

**Comment by wjessup** [comment]
@donmccurdy 

I'm having some confusion on this currently as well. 

I can't just set the material you suggest here: 

      mesh.traverse((node) => {
        if (node.isMesh) {
          node.material = this.material;
        }
      });

It throws an error "aframe-master.js:56153 Uncaught TypeError: Cannot set property 'value' of undefined at Mesh.refreshUniforms [as onBeforeRender] (aframe-master.js:56153)" 

however setting the shaders directly work fine. 

      mesh.traverse((node) => {
        if (node.isMesh) {
          node.material.vertexShader = vertexShader
          node.material.fragmentShader = fragmentShader
          node.material.needsUpdate = true
        }
      });

It seems in previous posts that if you iterate through the tree you should be able to set the materials directly but i'm unable to.  

I've already read / tested these approaches:
https://stackoverflow.com/questions/43914818/alpha-animation-in-aframe-for-a-object-model
https://github.com/donmccurdy/aframe-extras/blob/99535cd878eb36cb25cdcda4a32a40eb248c990a/src/misc/cube-env-map.js

**Comment by donmccurdy** [comment]
@wjessup you'll see that error if the glTF model is using a specular-glossiness PBR material. A-Frame and three.js do not have that material built in, and so a `mesh.onBeforeRender` callback is added to manage it. You'll need to remove that callback:

```js
  mesh.traverse((node) => {
    if (node.isMesh) {
      if (node.material.isGLTFSpecularGlossinessMaterial) {
        node.onBeforeRender = function () {};
      }
      node.material = this.material;
    }
  });
```

**Comment by wjessup** [comment]
you're a lifesaver! thanks :)

Is this documented anywhere and I missed it? I'm curious how I could have found it or debugged it myself.

**Comment by donmccurdy** [comment]
Hm, yeah this would be a hard one to have spotted without knowing that code... `mesh.onBeforeRender` is a callback meant for user-provided code, in this case added by the loader to support a PBR model three.js doesn't provide. The error [goes away](https://github.com/mrdoob/three.js/commit/5e4c7624017802a02361593e8c17d6519e4b8f73) in r90 (A-Frame 0.8) so I hope it won't be an issue for others.

**Comment by JoshuaCrisp** [comment]
@donmccurdy When I use this to replace my model's texture, my original mapping goes away. I am using this to have a character model change clothes, but the replacement outfit is all out of wack even though the png file has the same mapping dimensions. Any idea why this is?

**Comment by donmccurdy** [comment]
Could you make a demo? If you're loading textures with `TextureLoader` you will want to disable `flipY`.

```js
var textureLoader = new THREE.TextureLoader();
var texture = textureLoader.load('diffuse.png');
texture.flipY = false;
```

It may also be that your model has multiple materials, or some other material or texture settings involved.

**Comment by JoshuaCrisp** [comment]
Setting texture.flipY = false fixed it. Thank you!!

**Comment by javiTugboat** [comment]
@donmccurdy Hi Don. I've been trying to set a threejs material on a gltf model but seem to be in a dead end. I don't get any errors but the material is not placed.
this is my demo http://motiondolphins.com/app/index.html
any clues would be much appreciated!

**Comment by donmccurdy** [comment]
@javiTugboat the problem in your example is that the `object.traverse` code is never reached — you need to wait for the `model-loaded` event. For example:

```js
init: function () {
  this.el.addEventListener('model-loader', () => this.update());
},
update: function () {
  object = this.el.getObject3D('mesh');
  if (!object) return;
  object.traverse(() => {...});
}
```

**Comment by javiTugboat** [comment]
@donmccurdy Thanks Don. I have managed to call the update after the model is loading. However Now I get a range of errors http://motiondolphins.com/app/index.html. there must be a simple piece I'm missing...

**Comment by donmccurdy** [comment]
It's these lines:

```js
var texture = new THREE.TextureLoader().load( 'http://motiondolphins.com/app/models/baseColor.png' );

this.material  = new THREE.MeshStandardMaterial({
    map:"http://motiondolphins.com/app/models/baseColor.png", // error
    color : 0xffffff
});
this.el.addEventListener('model-loaded', () => this.update());
```

^ you need to assign `map: texture` rather than using the URL. :)

**Comment by javiTugboat** [comment]
I knew it was something obvious and silly haha. Thank you so much!

**Comment by rishabchorariapm** [comment]
Hi 

I am looking to build something on the lines of the link below-

https://www.kajariaceramics.com/tile_visualizer/ceramic_south.html

The user can change various floor and wall textures. I have been looking to use A-Frame and Three.js for this but i have failed. Can anyone guide me on the process of building something on these lines?

We have a design team that would work and create 3D designs. We would like to import them onto the webpage and allow users to edit them.
