### ISSUE TITLE
Trying to include the new FBXLoader with binary support

### ISSUE THREAD

**Issue by FuzzyWobble** [c-frame/aframe-extras#169]
here is the new FBX loader --> https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/FBXLoader.js

Now supports Binary and has some key bug fixes.

Possible to make it work with the FBX animation loader? I tried with no luck :(

**Comment by donmccurdy** [comment]
I just updated FBXLoader here to the latest version. Whether it will work with the model you have, I'm not sure – best of luck!
