### ISSUE TITLE
Cannot npm install

### ISSUE THREAD

**Issue by Rosefalk** [c-frame/aframe-extras#170]
Getting a cannon issue:

$ npm install --save aframe-extras
npm WARN peerDependencies The peer dependency cannon@github:donmccurdy/cannon.js       #v0.6.2-dev1 included from three-to-cannon will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! install but already installed versions [ '0.6.2' ]
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package cannon@0.6.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer three-to-cannon@1.1.1 wants cannon@github:donmccurdy/c       annon.js#v0.6.2-dev1

Removed personal data from the output.

**Comment by donmccurdy** [comment]
Hm, do you mind trying this with an updated version of npm?

```
npm update -g npm
npm install
```

If you need to stay on an older version of npm, you can later revert that with:

```
npm install -g npm@latest-2
```

**Comment by Rosefalk** [comment]
No problem.

Updating npm didn't do any difference, but updating node to newest stable did :) 👍
