### ISSUE TITLE
Prevent triggering events/movement when current checkpoint equals last one

### ISSUE THREAD

**Issue by paulocf92** [c-frame/aframe-extras#175]
I was reading through the docs and it's incredibly simple, and yet useful to have gaze-based interactions. Most apps will work for desktop, but touchless interactions won't benefit from this component. Would it be possible to add a property to allow gazing to trigger the movement? I believe a simple "gaze-timeout" parameter would be enough, if it's set then the user wants a gaze-based interaction, or maybe split in two components.

Thanks!

**Comment by donmccurdy** [comment]
The way to do gaze-based triggering is with `cursor="fuse: true"` ([example](https://aframe.io/docs/0.6.0/components/cursor.html#example)). When that's used, gazing triggers `click` events the same way that Cardboard, mouse button, or `laser-controls` presses would.

**Comment by paulocf92** [comment]
I did a small test in my project, but it's not behaving quite correctly actually. Maybe I'm missing something or need to prevent this myself, but if I gaze accidentally on the checkpoint element while it's animating, or while I'm already at it, it will try to trigger the movement again. This may not seem a problem, but it is... for example, I use the camera orientation upon landing on a checkpoint and having it re-trigger the movement causes bad behavior with that.

So, is there a way to prevent infinite gaze triggering by only allowing that to happen once? This should consider if I have already clicked the target and prevent any additional triggering on that element, both when traveling there and while remaining there; this could be a flag that clears itself when leaving the element and set to true when starting a movement towards a point.

Ehm, might be too much work but it makes a difference in my case, not sure how broad it will apply.

**Comment by donmccurdy** [comment]
Hm, I think I would need a demo showing what you mean. In [this example](https://sandbox.donmccurdy.com/checkpoints/) you can click the checkpoints multiple times and everything works fine; I don't think there's any reason gazing should behave differently?

**Comment by paulocf92** [comment]
Example: https://jsfiddle.net/5hndmauk/

A little errata from what I said: it doesn't trigger gaze multiple times while animating, only upon being at a checkpoint.

So, it's a little squishy because jsfiddle doesn't allow pointer lock. The test is to gaze into a cylinder and let the camera get there, once you're at a cylinder, move the cursor out of it (into an unoccupied space) and then move into it again. It keeps changing colors. It's like it's triggering every time the cursor re-enters the object's area. Not sure if there's a built-in way of preventing this.

It's not a hard test; when this ended up badly was because I accidentally reentered my checkpoint area, and it triggered navigation-end, incorrectly re-positioning a certain element which, in turn, depended on the original camera orientation and rotation. Probably a small edge case, but... >.<

**Comment by paulocf92** [comment]
Maybe don't trigger movement if target checkpoint is equal to current? This would permanently solve this.

**Comment by donmccurdy** [comment]
Sounds good, thanks!
