### ISSUE TITLE
Changing target checkpoint while animating ends previous animation with wrong checkpoint

### ISSUE THREAD

**Issue by paulocf92** [c-frame/aframe-extras#176]
In the file `checkpoint-controls.js`, at line 29, you have this:
`el.emit('navigation-end', {checkpoint: checkpoint});`

I'm almost sure you meant `checkpoint: this.checkpoint` to pass old checkpoint, the way it is now it's implying the previous movement ended with new target, but we're just starting to move towards the new one. I'm trying to make something manually to come up with the behavior mentioned in #175, and now I realized I won't be able to do that because of this little bug.

I'm almost reaching my issue quota related to this component. heh

Thank you.

**Comment by donmccurdy** [comment]
You are right, thanks! :)
