### ISSUE TITLE
GSAP AttrPlugin for A-Frame?

### ISSUE THREAD

**Issue by donmccurdy** [c-frame/aframe-extras#182]
Greensock has plugins, like [AttrPlugin](https://greensock.com/docs/Plugins/AttrPlugin) to support animating non-CSS properties. Would be great to have an AframePlugin equivalent, that lets you animate A-Frame's component properties, like:

```js
TweenLite.to("#foo", 1, {aframe:{position: {x: 0, y: 1, z: 2}}, ease:Linear.easeNone});
```

**Comment by mzpq01** [comment]
So is there such a plugin today?

**Comment by donmccurdy** [comment]
Not that I'm aware of, sorry. I've closed this because I don't plan to create one myself.

**Comment by mzpq01** [comment]
> Not that I'm aware of, sorry. I've closed this because I don't plan to create one myself.

ah i see. but can we use attrPlugin as illustrated in its doc? For example:
`<a-box id="box" position="0 0 0" scale="1 1 1 " rotation="0 0 0"></a-box>`
`TweenLite.to("#box", 1, {attr:{position:10 5 -5, scale:2 2 2, rotation:0 180 0}, ease:Linear.easeNone});`
is this possible?

**Comment by donmccurdy** [comment]
No idea! 😇

**Comment by mzpq01** [comment]
> No idea! 😇

Thanks for the quick reply! I'll test is myself. 😈

**Comment by shujathkhan** [comment]
> > No idea! 😇
> 
> Thanks for the quick reply! I'll test is myself. 😈

@mzpq01 So did it work  ?
