### ISSUE TITLE
怎么在 a-frame 的渲染器里面加载three.js导出的scene.json场景文件

### ISSUE THREAD

**Issue by 2daye** [c-frame/aframe-extras#184]
我想在 a-frame 里面的<a-scene>渲染器记载渲染three.js导出的scene.json场景文件，我应该怎么做？请求帮助，谢谢！

**Comment by 2daye** [comment]
I want the renderer in A-frame to record the scene.json scene files that render the three.js export. What should I do? Asking for help, thank you!

**Comment by 2daye** [comment]
Can you read what I said? I'm a developer of China

**Comment by 2daye** [comment]
How do I load three.js exported scene.json scene files inside <a-scene>?

**Comment by donmccurdy** [comment]
Hi @2daye —

A-Frame can load three.js JSON files using one of two components: `json-model` and `object-model`. Here is an example using `json-model` ([source code](https://github.com/donmccurdy/aframe-extras/blob/v3.11.0/examples/animation/index.html#L23), [demo](https://sandbox.donmccurdy.com/animation/)). [Documentation](https://github.com/donmccurdy/aframe-extras/tree/master/src/loaders).

There is more than one kind of three.js `.json` file, so you will probably need to try both `json-model` and `object-model` to see which one works. If that doesn't work, you might also want to try exporting with THREE.GLTFExporter (to create a `.gltf` file) or THREE.OBJExporter (to create an `.obj` file).

**Comment by 2daye** [comment]
Thank you very much for helping me！

**Comment by 2daye** [comment]
I've passed three.js's THREE.ObjectLoader ()

**Comment by 2daye** [comment]
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="js/aframe.js"></script>
    <title>A-Frame</title>
</head>
<body>
<a-scene school-playground></a-scene>
</body>
<script type="text/javascript"></script>
<script type="text/javascript">
    AFRAME.registerComponent('school-playground', {
        init: function () {
            this.model = null;
        },

        update: function () {
            var scene;
            loader = new THREE.ObjectLoader();
            loader.load("scene.json", function (object) {
                object.traverse(function (o) {
                    if (o instanceof THREE.SkinnedMesh && o.material) {
                        o.material.skinning = !!((o.geometry && o.geometry.bones) || []).length;
                    }
                });
                this.load(object);
            }.bind(this));
        },

        load: function (model) {
            this.model = model;
            this.el.setObject3D('mesh', model);
            this.el.emit('model-loaded', {format: 'json', model: model});
        },

        remove: function () {
            if (this.model) this.el.removeObject3D('mesh');
        }

    });
</script>
</html>

**Comment by 2daye** [comment]
(https://github.com/donmccurdy/aframe-extras/blob/v3.11.0/examples/animation/index.html#L23)
I didn't try to succeed

**Comment by 2daye** [comment]
I don't know. What is aframe-extras.js?

**Comment by donmccurdy** [comment]
> I don't know. What is aframe-extras.js?

It is the aframe-extras package. You can install it as described here: https://github.com/donmccurdy/aframe-extras#usage-scripts

**Comment by 2daye** [comment]
Using aframe-extras.js to load scene.json, aframe-extras.js:22370 Uncaught ReferenceError: THREE is not defined appears

**Comment by 2daye** [comment]
Uncaught ReferenceError: THREE is not defined

**Comment by donmccurdy** [comment]
@2daye it sounds like you have the wrong `aframe-extras.js` file, or have forgotten to include the A-Frame script first. Please post a demo on Codepen, JSFiddle, Neocities, or somewhere else like that.

**Comment by donmccurdy** [comment]
a typical way to set things up would be:

```html
<script src="https://aframe.io/releases/0.7.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/donmccurdy/aframe-extras/v3.12.4/dist/aframe-extras.min.js"></script>
```

**Comment by 2daye** [comment]
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport"
          content="width=device-width,initial-scale=1,shrink-to-fit=no,user-scalable=no,maximum-scale=1">
    <title>Examples • Animation</title>
    <script src="js/aframe.js"></script>
    <script src="js/aframe-extras.js"></script>
</head>
<body>
<a-scene>
    
    <a-entity camera="userHeight: 1.6"
              universal-controls
              position="0 0 5">
    </a-entity>
    
    <a-entity scale="0.035 0.035 0.035"
              rotation="0 90 0"
              animation-mixer="clip: *;"
              json-model="src: url(scene.json);">
    </a-entity>

    
    <a-grid></a-grid>

    
    <a-light type="ambient" color="#bbb"></a-light>
    <a-light color="#ccc" position="0 30 0" distance="100" intensity="0.4" type="point"></a-light>
    <a-light color="#ccc" position="3 10 -10" distance="50" intensity="0.4" type="point"></a-light>
</a-scene>
</body>
</html>

**Comment by 2daye** [comment]
A-Frame Version: 0.7.0 (Date 22-09-2017, Commit #570c623e)
aframe.js:78459 three Version: ^0.87.0
aframe.js:78460 WebVR Polyfill Version: ^0.9.36
aframe.js:26648 THREE.WebGLRenderer 87
aframe-extras.js:7413 [physics] `debug` cannot be changed dynamically.
update @ aframe-extras.js:7413
module.exports.System @ aframe.js:77295
NewSystem @ aframe.js:77399
value @ aframe.js:76178
bound @ aframe.js:79938
value @ aframe.js:76168
value @ aframe.js:76122
wrappedMethod @ aframe.js:75142
aframe.js:39174 THREE.JSONLoader: scene.json should be loaded with THREE.ObjectLoader instead.
(anonymous) @ aframe.js:39174
(anonymous) @ aframe.js:35819
XMLHttpRequest.send (async)
load @ aframe.js:35875
load @ aframe.js:39161
update @ aframe-extras.js:24144
updateProperties @ aframe.js:75428
module.exports.Component @ aframe.js:75219
NewComponent @ aframe.js:75618
value @ aframe.js:74104
value @ aframe.js:74271
Object.create.updateComponents.value @ aframe.js:74238
entityLoadCallback @ aframe.js:74033
emitLoaded @ aframe.js:74854
Promise resolved (async)
value @ aframe.js:74852
value @ aframe.js:74029
value @ aframe.js:73807
wrappedMethod @ aframe.js:75142
cdn.rawgit.com/donmccurdy/aframe-extras/v1.16.3/assets/grid.png:1 GET https://cdn.rawgit.com/donmccurdy/aframe-extras/v1.16.3/assets/grid.png net::ERR_INSECURE_RESPONSE
Image (async)
checkIsImage @ aframe.js:80853
validateSrc @ aframe.js:80769
loadTexture @ aframe.js:79479
module.exports.updateMapMaterialFromData @ aframe.js:80637
module.exports.updateMap @ aframe.js:80662
init @ aframe.js:78931
updateShader @ aframe.js:69104
update @ aframe.js:69051
updateProperties @ aframe.js:75428
module.exports.Component @ aframe.js:75219
NewComponent @ aframe.js:75618
value @ aframe.js:74104
value @ aframe.js:74271
Object.create.updateComponents.value @ aframe.js:74238
entityLoadCallback @ aframe.js:74033
emitLoaded @ aframe.js:74854
Promise resolved (async)
value @ aframe.js:74852
value @ aframe.js:74029
value @ aframe.js:73807
wrappedMethod @ aframe.js:75142
wrappedMethod @ aframe.js:75142
aframe.js:24516 THREE.WebGLRenderer: Texture is not power of two. Texture.wrapS and Texture.wrapT should be set to THREE.ClampToEdgeWrapping. VideoTexture {uuid: "868A9C65-1FC0-4027-85D3-46B51DF20152", name: "", image: video, mipmaps: Array(0), mapping: 300, …}
setTextureParameters @ aframe.js:24516
uploadTexture @ aframe.js:24582
setTexture2D @ aframe.js:24362
setTexture2D @ aframe.js:28894
setValueT1 @ aframe.js:10246
WebGLUniforms.upload @ aframe.js:10565
setProgram @ aframe.js:28457
WebGLRenderer.renderBufferDirect @ aframe.js:27271
renderObject @ aframe.js:28001
renderObjects @ aframe.js:27974
WebGLRenderer.render @ aframe.js:27738
render @ aframe.js:81688
value @ aframe.js:76655
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
startRender @ aframe.js:76544
(anonymous) @ aframe.js:76528
module.exports.fireEvent @ aframe.js:80419
value @ aframe.js:74965
emitLoaded @ aframe.js:74855
Promise resolved (async)
value @ aframe.js:74852
value @ aframe.js:74029
(anonymous) @ aframe.js:76553
aframe.js:25822 WebGL: INVALID_VALUE: texImage2D: no video
texImage2D @ aframe.js:25822
uploadTexture @ aframe.js:24712
setTexture2D @ aframe.js:24362
setTexture2D @ aframe.js:28894
setValueT1 @ aframe.js:10246
WebGLUniforms.upload @ aframe.js:10565
setProgram @ aframe.js:28457
WebGLRenderer.renderBufferDirect @ aframe.js:27271
renderObject @ aframe.js:28001
renderObjects @ aframe.js:27974
WebGLRenderer.render @ aframe.js:27738
render @ aframe.js:81688
value @ aframe.js:76655
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
requestAnimationFrame (async)
requestAnimationFrame @ aframe.js:81481
value @ aframe.js:76654
bound @ aframe.js:79938
startRender @ aframe.js:76544
(anonymous) @ aframe.js:76528
module.exports.fireEvent @ aframe.js:80419
value @ aframe.js:74965
emitLoaded @ aframe.js:74855
Promise resolved (async)
value @ aframe.js:74852
value @ aframe.js:74029
(anonymous) @ aframe.js:76553
196w.html:1 [.Offscreen-For-WebGL-00000186888C5140]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
w.html:1 GET https://cdn.rawgit.com/donmccurdy/aframe-extras/v1.16.3/assets/grid.png net::ERR_INSECURE_RESPONSE
aframe.js:3217 components:texture:warn `$s` is not a valid video  https://cdn.rawgit.com/donmccurdy/aframe-extras/v1.16.3/assets/grid.png
59w.html:1 [.Offscreen-For-WebGL-00000186888C5140]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
w.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.

**Comment by 2daye** [comment]
I don't know, is it, can't load it, or use three.js?

**Comment by 2daye** [comment]
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="js/aframe.js"></script>
    <title>A-Frame</title>
</head>
<body>
<a-scene school-playground></a-scene>
</body>
<script type="text/javascript"></script>
<script type="text/javascript">
    AFRAME.registerComponent('school-playground', {
        init: function () {
            this.model = null;
        },

        update: function () {
            var scene;
            loader = new THREE.ObjectLoader();
            loader.load("scene.json", function (object) {
                object.traverse(function (o) {
                    if (o instanceof THREE.SkinnedMesh && o.material) {
                        o.material.skinning = !!((o.geometry && o.geometry.bones) || []).length;
                    }
                });
                this.load(object);
            }.bind(this));
        },

        load: function (model) {
            this.model = model;
            this.el.setObject3D('mesh', model);
            this.el.emit('model-loaded', {format: 'json', model: model});
        },

        remove: function () {
            if (this.model) this.el.removeObject3D('mesh');
        }

    });
</script>
</html>

**Comment by 2daye** [comment]
So it can be loaded

**Comment by 2daye** [comment]
It can be loaded by writing like this

**Comment by donmccurdy** [comment]
Please post a demo online, using Neocities or Codepen or JSFiddle or something like that. Sorry, I can't debug code for you in a GitHub issue like this.

**Comment by donmccurdy** [comment]
Also note the error in your logs that says:

```
aframe.js:39174 THREE.JSONLoader: scene.json should be loaded with THREE.ObjectLoader instead.
```

you should be either using THREE.ObjectLoader, or my `object-model` component...

**Comment by 2daye** [comment]
Thank you very much for helping me!

**Comment by 2daye** [comment]
I used the object-model component you said and successfully loaded the scene.json scene

**Comment by 2daye** [comment]
Thank you very much!

**Comment by 2daye** [comment]
One more question. Does A-Frame's <a-scene> scene have a camera and a light by default?

**Comment by donmccurdy** [comment]
It does, yes: https://aframe.io/docs/0.7.0/core/scene.html

**Comment by 2daye** [comment]
Well thank you very much!

**Comment by 2daye** [comment]
@donmccurdy So the default, the light, the camera, can you get rid of it?

**Comment by donmccurdy** [comment]
See the a-frame docs for how to get rid of default lights: https://aframe.io/docs/0.7.0/components/light.html

There must be a `camera` somewhere in the scene. If you include your own the default won’t be added.

**Comment by 2daye** [comment]
Thank you. I've solved it.

**Comment by 2daye** [comment]
https://aframe.io/a-painter/，I also want to ask how this game is moving （HTC Vive） Handle move function

**Comment by 2daye** [comment]
https://aframe.io/a-painter/（我也想问一下这款游戏如何移动（HTC Vive）手柄移动功能）

**Comment by 2daye** [comment]
我也想问一下这款游戏如何移动（HTC Vive）手柄移动功能 https://aframe.io/a-painter/

**Comment by donmccurdy** [comment]
That's a more general question, you should probably ask on https://github.com/aframevr/a-painter or in Slack.

**Comment by 2daye** [comment]
OK, I'll go and ask him. Thank you.

**Comment by 2daye** [comment]
@donmccurdy A-Frame Loaded obj model can be used <a-animation> Do you add spin?

**Comment by donmccurdy** [comment]
I don't think I understand?
