### ISSUE TITLE
sphere-collider default might be to target only top-level entities

### ISSUE THREAD

**Issue by wmurphyrd** [c-frame/aframe-extras#191]
Brought to my attention in wmurphyrd/aframe-super-hands-component#115

https://github.com/donmccurdy/aframe-extras/blob/95d3483013bc9b774ab4fe5c4525b042f4e39812/src/misc/sphere-collider.js#L63

Does `parentNode.children` include descendants or only direct children?

**Comment by donmccurdy** [comment]
Yeah, that will only be top-level elements. Although the size of the descendants are considered in the collision detection. I guess the question might be, given this:

```html
<a-scene>
  <a-gltf-model ...>
    <a-entity id="no-content"></a-entity>
   </a-gltf-model>
  <a-entity>
    <a-gltf-model ...></a-gltf-model>
  </a-entity>
</a-scene>
```

... which things should be collided with by default, and are duplicate events on parent and child OK, given the events bubble anyway?

**Comment by wmurphyrd** [comment]
I think the use case that this interferes with is more like

```html
<a-entity id="container" position="0 1.6 -3">
  <a-entity grabbable></a-entity>
  <a-entity grabbable></a-entity>
</a-entity>
```

Neither of the `grabbable` entities would be interactable under the current default as `sphere-collider` would register hits and emit events only on the parent, and, even if the parent events were listened to, it wouldn't differentiate which child was collided. 

However, considering this issue, performance, and other issues arising from collidee list default values (aframevr/aframe#3262), maybe the best long-term solution for all collision detection components is to make the `objects` specification required.
