### ISSUE TITLE
mouse-controls component does not work independently of universal-controls

### ISSUE THREAD

**Issue by MilesMcBain** [c-frame/aframe-extras#193]
I apologise if this is by design and I have misunderstood. If add the `mouse-controls` component to my player entity I get the pointer disappearing on click, but I still need to hold down a mouse button and drag to rotate the view. I thought the idea was that pointer lock was on by default. Using `universal-controls` for pointer lock works as I would expect. 

Here is an example of `mouse-controls` working as I describe: https://glitch.com/edit/#!/rapid-basket?path=index.html:11:30

**Comment by donmccurdy** [comment]
None of the controls in this package can work independently of `universal-controls` — if you want to use just one, you could do something like [this](https://github.com/donmccurdy/aframe-extras/tree/master/src/controls#usage) —

```html
<a-entity camera universal-controls="rotationControls: mouse;"></a-entity>

<a-entity camera universal-controls="rotationControls: mouse;" mouse-controls></a-entity>
```

Either of those will work; in the first case `mouse-controls` is added automatically.

**Comment by MilesMcBain** [comment]
Okay that's clear, thanks!
