### ISSUE TITLE
[Question] using kinematic-body with a Terrain heightmap

### ISSUE THREAD

**Issue by arpu** [c-frame/aframe-extras#195]
the kinematic-body work perfect with a static wall body-static 
but how can i use this with a heightmap of the Terrain ? 
(like https://github.com/IceCreamYou/THREE.Terrain mountens)

**Comment by arpu** [comment]
works fine with shape:mesh

**Comment by donmccurdy** [comment]
The physics system can't automatically build a heightmap right now (see https://github.com/donmccurdy/three-to-cannon/issues/1) but maybe later... in the meantime a mesh may work, or i'm working on getting navigation meshes supported so that you don't need physics at all for this.

**Comment by arpu** [comment]
maybe a other idea is to use https://github.com/yomotsu/meshwalk.js ?

**Comment by donmccurdy** [comment]
Nice! I hadn't seen that. Jumping seems to work nicely... I wish there were documentation on what kind of terrain models it allows.
