### ISSUE TITLE
Dist files are not compiled to ES5

### ISSUE THREAD

**Issue by RSpace** [c-frame/aframe-extras#200]
The dist files includes code such as "class" (unsupported in IE11) and "const" (unsupported in IE10). I realize aframe does not officially support any version of Internet Explorer, but getting IE11 support is quite trivial and something I need to maintain on my project. I'm not targeting IE10 support, however, I do try to avoid syntax errors so I can display a nice error message in IE10 instead of just failing when my scripts are parsed.

Previous versions of aframe-extras did not have this problem (at least not in IE11), and the "class" statements in the dist files seems to have been introduced by the recent addition of pathfinding.

I'm sorry to submit an issue instead of a PR, but I'm not really familiar with browserify and your build setup looks very custom. I'm guessing it's just a matter changing the build target to ES5 somewhere, but I can't figure out where that is.

**Comment by RSpace** [comment]
Perhaps it's related to https://github.com/donmccurdy/aframe-extras/issues/154 ?

**Comment by donmccurdy** [comment]
Ah, yeah I’m migrating this repo for v4 but probably should have waited to add that dependency and set up babelify first.... the build is pretty custom but i think it’s fixable. 

Not really making any effort to support IE10, given no WebGL, but having dist files in ES5 seems reasonable yeah.

**Comment by donmccurdy** [comment]
^Will be fixed in v4.0.0.
