### ISSUE TITLE
Angular4 plus Aframe extras?

### ISSUE THREAD

**Issue by GrandmasterGrogu** [c-frame/aframe-extras#204]
Hey,

Anyone successful at doing A-frame extras with Angular4? I am able to do A-frame with it, but extras does not seem to work. 

If I figure it out, I'll post back here.

**Comment by donmccurdy** [comment]
I haven't tried this, but best of luck. There could be issues if you're using Webpack, as one of the dependencies doesn't bundle nicely.

**Comment by donmccurdy** [comment]
Closing for now, but I’d be interested to hear if there are issues or special steps needed.
