### ISSUE TITLE
Support for a-animation component in A-Frame

### ISSUE THREAD

**Issue by JoshuaCrisp** [c-frame/aframe-extras#210]
Currently, attempting to change the active clip using a-animation in a-frame causes gltf2 models to revert to the TPose. It would be wonderful if we could do this:

`<a-animation>
             attribute="animation-mixer"
             to="clip: newClip; loop: newLoopValue; crossFadeDuration: newDuration: etc."
             begin= "namedEmit"
 </a-animation>`

**Comment by donmccurdy** [comment]
I'm not sure what `<a-animation/>` does with strings, it's more for tweening... 

Have you tried using [event-set](https://www.npmjs.com/package/aframe-event-set-component)?

```html
<a-entity animation-mixer event-set__click="animation-mixer.clip: run"></a-entity>
```

**Comment by donmccurdy** [comment]
I'm not sure I understand the issue you're describing. Are you saying you see the TPose between when the walking clip ends and the idle clip begins? or the model goes to TPose after the idle clip ends, and you want it to freeze in the last frame of the idle clip? could you describe the behavior you get, and the behavior you want, and/or create a demo?

**Comment by arpu** [comment]
between the two animations

**Comment by arpu** [comment]
https://socialvr.vreen.live/dev
if you open two instances and walk around you see the tpose

**Comment by arpu** [comment]
if its needed i can make a smaller example

**Comment by donmccurdy** [comment]
Having a difficult time loading that example, yeah something simpler would be best. Here's one I've made, cycling between idle and run animations:

https://aframe-animation-crossfade-yxktsdzbpn.now.sh/

Note that I'm setting a bit of a crossfade on the two clips:

```html

<a-entity position="0 1 0"
  animation-mixer="clip: Idle; crossFadeDuration: 0.5;"
  gltf-model="src: url(xbot.gltf);">
  </a-entity>
```

If you have no crossfade, it's possible you'll see the T-Pose between clips, probably depending on how the model is keyframed...  my model here _does_ have a T-Pose, but it's not shown between clips. Hopefully that example is enough to help but feel free to add details if not!

**Comment by arpu** [comment]
awesome the crossFadeDuration: 0.5 fixed it for me!
thx a lot!
