### ISSUE TITLE
<a-hexgrid> primitive not loading hexmap JSON assets

### ISSUE THREAD

**Issue by dsinni** [c-frame/aframe-extras#211]
`<a-hexgrid/>` does not work with any of the following:

```
          src="#hexmap"
          src="url(#hexmap)"
          src="hexmap.json"
          src="url(hexmap.json)"
```
[See Reproduction](https://thimbleprojects.org/dsinni/411496/)

In fact, a hexgrid only appears when no src is set (`src=""`), assuming it's to a default mesh value.

When a src is set, the error below is thrown:

`TypeError: this.addMesh is not a function[Learn More] aframe-extras.min.js:1:288442`

I'm currently using `aframe` `0.7.1` and `aframe-extras` `3.13.1`, but I haven't had luck with previous versions, either, or at least haven't found a working combination.

See comments in the Thimble `index.html` for more notes.

**Comment by donmccurdy** [comment]
This has been fixed on the master branch, any of the things you tried above should work. The branch isn't quite stable yet, so YMMV switching over before next release.

**Comment by dsinni** [comment]
Right on. I'll give it a go in the morning. Thanks for the speedy response, Don.
