### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by n0Sp00n** [c-frame/aframe-extras#212]
Trying to implement the navigation controller on the camera (_a.k.a the player_) but I am unable to do that, because the of lack of documentation.

Is it possible to put some basic documentation about the main components and properties, how do they work, what arguments are required, really helpful is to indicate the type (_v3, int, bool_).

Thank you in advance.
Cheers!

**Comment by donmccurdy** [comment]
thanks for the reminder! will get to it before the next release, meanwhile here's an example use i had sitting in a test scene:

```html
<a-scene>
  <a-sky color="#FFF"></a-sky>

  <!-- Player -->
  <a-entity camera="userHeight: 1.6"
            universal-controls="constrainToNavMesh: true"
            position="0 0 5">
  </a-entity>

  <!-- Nav mesh -->
  <a-entity gltf-model="src: url(../assets/tmp/inn/inn_navmesh.gltf)"
            nav-mesh
            visible="false"></a-entity>

  <!-- Scene -->
  <a-entity gltf-model="src: url(../assets/tmp/inn/scene.gltf)"
            position="-34.968 -5 -1.416"
            scale="0.1 0.1 0.1"></a-entity>
</a-scene>
```

**Comment by donmccurdy** [comment]
Different scene, with demo: https://aframe-assetforge-pvjcvuphpf.now.sh/

**Comment by n0Sp00n** [comment]
Thank you very much mate!
Let me know if I can help with anything else : ]

**Comment by n0Sp00n** [comment]
Unfortunately the provided snippet of code does not work.

**Comment by donmccurdy** [comment]
Compare to the live demo? It is working there — but does depend on the setup of the navigation mesh, and this assumes (1) master version of aframe-extras, and (2) aframe 0.7.0. Could also break if you try to scale or reposition the navigation mesh, which currently must be at the origin.

**Comment by n0Sp00n** [comment]
Hi.

I downloaded the _aframe-extras_ and compiled the scripts. I use the bundle right now, probably in future I'll use the _cdn_ once you release the new version.

My issue was that for some reason the navigation mesh wasn't good. I downloaded a different model and generated a navigation mesh for it again. And this time it worked.
Here's a demo: https://www.useloom.com/share/76eec020eea847059c937bf7d158bb73

Thank you for support.
Cheers!

**Comment by dsinni** [comment]
@donmccurdy: Is the transpiled version of `master` hosted anywhere officially, or do we need to transpile it manually? Thanks in advance.

**Comment by donmccurdy** [comment]
@dsinni only on releases, so not yet. if you want to do that manually:

```
// clone or download ZIP, then...
npm install
npm run dist
```

**Comment by donmccurdy** [comment]
I've updated aframe-extras for A-Frame 0.8.0, and written documentation of some (significant) changes to the controls. See: https://github.com/donmccurdy/aframe-extras/tree/master/src/controls

These changes are still on master; there is no new release of aframe-extras quite yet.
