### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'DOM_KEY_LOCATION_STANDARD' of function 'function KeyboardEvent

### ISSUE THREAD

**Issue by gitzhang** [c-frame/aframe-extras#216]
A-Frame Version: 0.8.0 (Date 2018-03-09, Commit #c4f2425)
three Version: github:dmarcos/three.js#r90fixPose
WebVR Polyfill Version: ^0.9.40
keyboard.polyfill.js:15 Uncaught TypeError: Cannot assign to read only property 'DOM_KEY_LOCATION_STANDARD' of function 'function KeyboardEvent() { [native code] }'

**Comment by donmccurdy** [comment]
Are you seeing this issue with A-Frame 0.7.X as well, or just 0.8.0?

**Comment by donmccurdy** [comment]
Or, what browser?

**Comment by donmccurdy** [comment]
Sorry, I can't reproduce this issue without more information.
