### ISSUE TITLE
[kinematic-body] scene shakes / bounces

### ISSUE THREAD

**Issue by rmrbytes** [c-frame/aframe-extras#225]
The following has been observed. 

Periodically (every few seconds) the whole scene seems to jump (bounce/shake) up and down with the following versions.
`aframe v0.8.2`
`aframe-extras v4.0.2`
`aframe-physics-system v2.0.1`

A glitch project has been created to demonstrate the same:
https://short-canoe.glitch.me/

**Comment by rmrbytes** [comment]
I just tried the following in the same glitch project.

a. changed the aframe ver to 0.7.1
b. changed the aframe-extras to 3.13.1
c. removed the aframe-physics (since it is part of extras v 3.13.1)
d. removed the rig
e. changed the look-controls to universal-controls

and the shaking stops

And this is my first use of physics so am not familiar with any earlier versions

**Comment by dsinni** [comment]
For what it's worth, here is another demo of the "bouncing": https://codepen.io/dansinni/pen/MGYwWK

**Comment by Healz4Life** [comment]
This has also been a big issue for me as well, along with much worse shakiness when the player is bigger or smaller then a size around 3, flinging backwards around size 2 and floating when you look above the middle of the screen at size 0.3, though that seems to have to do more with the super-hands component. There's a 3 month competition I've been doing so the example I have is a bit more complex but here it is if you wish to see it: https://freddykruggor.gitlab.io/Project_X . Still not quite finished. Two more notes, if you put a box on another box it will have the same shakiness the player does until the box on top falls off the one beneath it, as well the player doesn't shake as much when moving.

**Comment by Healz4Life** [comment]
I'll try that out. Thanks for the advice and keep up the good work :)

**Comment by donmccurdy** [comment]
Also — here's a (very) experimental thing I'm working on that's worth a try. I'm writing a plugin for the A-Frame inspector that builds a navmesh for the current scene.

Steps:

1. Add script.

```html
<script src="https://recast-api.donmccurdy.com/aframe-inspector-plugin-recast.js"></script>
```

2. Add plugin component to scene.

```html
<a-scene inspector-plugin-recast> ... 
```

3. Open inspector, configure, and press "Build".

![screen shot 2018-05-01 at 7 45 36 pm](https://user-images.githubusercontent.com/1848368/39503050-74d92ce4-4d78-11e8-9aba-698a3bbcf82c.png)


4. Export navmesh, and use it in a scene with the [usual instructions](https://github.com/donmccurdy/aframe-extras/tree/master/src/pathfinding).

> EDIT: Repo for bug reports: https://github.com/donmccurdy/aframe-inspector-plugin-recast

**Comment by rmrbytes** [comment]
Thanks @donmccurdy . 

I just tried on a simple scene: floor + 4 walls + one box at the centre. Opened Inspector. Clicked on the scene. Clicked on Build. After a few seconds gave an error. Console showed.

![screen shot 2018-05-02 at 8 43 41 am](https://user-images.githubusercontent.com/14859054/39503743-2dcb9a72-4de5-11e8-8f6d-d84a767bd8d3.png)

The glitch is: https://glitch.com/edit/#!/magnificent-columnist

**Comment by donmccurdy** [comment]
Hm looks like `a-sky` is breaking it. Removing that and shuffling things around a bit gives some results:

![screen shot 2018-05-01 at 8 37 23 pm](https://user-images.githubusercontent.com/1848368/39504310-8b8dcc90-4d7f-11e8-9ad4-834eec677fce.png)

But anyway, yeah, it's likely to have a lot of rough edges right now. 😅

**Comment by rmrbytes** [comment]
Hmm. Can you please share the glitch of the above. I am still getting a no navigation-mesh error after build when I click on Export.

![screen shot 2018-05-02 at 9 16 20 am](https://user-images.githubusercontent.com/14859054/39504480-8b809ca4-4de9-11e8-9251-1ae0b65aa16a.png)

I added an `<a-entity nav-mesh></a-entity>` to the scene too. Tried w/ wo the entity. What am I doing wrong?

And appreciate the plug-in even if it has a few rough edges for now.

**Comment by donmccurdy** [comment]
Now I think your grid is just too small, and the barriers too low, for the default navmesh parameters. Otherwise it's fine, you don't have to include a `nav-mesh` component.

Here's one I've adjusted a bit:

https://cherry-teacher.glitch.me/

note how it goes over the lower barriers, because of the `agentMaxClimb` setting:

![screen shot 2018-05-01 at 8 59 54 pm](https://user-images.githubusercontent.com/1848368/39504741-a74c88c4-4d82-11e8-943c-5d9d88445079.png)

**Comment by rmrbytes** [comment]
ok. Thanks. will check it

**Comment by rmrbytes** [comment]
@donmccurdy : This works well. Thanks. 

Why does the plug-in require a larger `<a-grid>`. In the example, the room size is 3x3 but if I set the grid size to be 5x5, if fails, while if I change it to 10x10 it works.

**Comment by donmccurdy** [comment]
Not sure. 😁 Guessing that if your `agentRadius` is `0.2` then you need passages of at least `0.4`, and enough buffer to allow for approximation errors. Which you _should_ have in the 3x3 grid, but maybe not. This is using the [Recast library](https://github.com/recastnavigation/recastnavigation), and I don't know the details about how it works.

**Comment by donmccurdy** [comment]
If you'd like to report bugs, the repo is here: https://github.com/donmccurdy/aframe-inspector-plugin-recast

**Comment by rmrbytes** [comment]
ok. will study that library and report a bug if necessary. Thanks

**Comment by dsinni** [comment]
Amazing stuff, @donmccurdy!

**Comment by dsinni** [comment]
Hi, @donmccurdy. Just wanted to check in to see if any progress has been made on this front.

I know there's a big push for using `nav-mesh`, but the `kinematic-body` route still makes the most sense for certain use cases.

As @rrrepos stated, it worked well enough with A-Frame `0.7.1` and `aframe-extras` `3.13.1`, but kind of regressed with the newer versions of each, including `aframe-physics-system`.

Aside from `kinematic-body`, I've also noticed that if you stack a bunch of boxes with `dynamic-body`, there is much more movement. I've played with the `restitution` value and such with no luck.

At this point, do you think it likely to achieve the working state of `3.13.1` (or better) with newer versions of A-Frame?

Thanks, man.

**Comment by dsinni** [comment]
I'll put some together and post here. Thanks for the reply, Don.

**Comment by dsinni** [comment]
That stress test link appears to be using A-frame `0.6.0` and a `3.*.*` version of `aframe-extras`, which was pretty stable by comparison. I'll show the comparison when I post. Thanks again.

**Comment by donmccurdy** [comment]
> That stress test link appears to be using A-frame 0.6.0 and a 3.*.* version ...

Ah good point, I should definitely update all those test cases anyway... at first look the boxes still seem stable with A-Frame 0.8.2, but yeah more examples would be appreciated. 👍

**Comment by donmccurdy** [comment]
The `kinematic-body` component should be more stable in the next release, with the caveat that jumping is disabled by default. You can restore that option with `kinematic-body="enableJumps: true"` (in addition to using `jump-ability`), but doing so will make the player more "shaky" again.
