### ISSUE TITLE
Allow A-Frame primitive geometries to act as `nav-mesh`

### ISSUE THREAD

**Issue by dsinni** [c-frame/aframe-extras#226]
It would be great if it were possible to allow A-Frame (or three.js) primitive geometries to act as nav meshes. As it is now, it doesn't seem possible.

Example:
```
<a-entity geometry="primitive: plane; height: 100; width: 50;" rotation="-90 0 0" nav-mesh></a-entity>
```

**Comment by donmccurdy** [comment]
Thanks, I like this idea. The nav mesh really needs to be a single mesh, so it would be just one plane supported, but that should be feasible.

**Comment by dsinni** [comment]
Right, understood. I think even that would be useful, especially if a custom geometry could be used via `AFRAME.registerGeometry()`.

**Comment by dirkk0** [comment]
Is there a way to concatenate planes?
I am able to move into the yellow section but not back - what would be the proper way to do this?


    <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/donmccurdy/aframe-extras@v6.0.1/dist/aframe-extras.min.js"></script>

    <body>
      <a-scene renderer="gammaOutput: true" background="color: lightblue;">

        
        <a-entity id="rig" movement-controls="constrainToNavMesh: true;">
          <a-entity camera look-controls="pointerLockEnabled: true;" position="0 1.6 0"></a-entity>
        </a-entity>

        
        <a-entity scale="0.5 1 1">
          <a-entity geometry="primitive: plane; height: 10; width: 10;" material="color: indigo; side: double;"
            rotation="-90 0 0" nav-mesh></a-entity>
            <a-entity position="10 0 0" geometry="primitive: plane; height: 4; width: 10;" material="color: yellow; side: double;"
            rotation="-90 0 0" nav-mesh></a-entity>
        </a-entity>

      </a-scene>


    </body>

**Comment by donmccurdy** [comment]
Not very easily, no. Merging the geometry would not be enough, because the vertices need to be fully connected as well. You may find it easier to trace out the shape in Blender, even just by hand, for the area you want.

**Comment by dirkk0** [comment]
![image](https://user-images.githubusercontent.com/625394/67272865-978b5d00-f4bd-11e9-82a2-a6fb3f81d9b7.png)
Ah!  Create a plane in Blender, cut it with the knife tool, export to gltf and - voila!
Works like a charm!
Thanks!
