### ISSUE TITLE
Play Audio on Marker Detection

### ISSUE THREAD

**Issue by peterlunglum** [c-frame/aframe-extras#227]
I'm trying to play sound when a marker is detected but it currently isn't working.
From other issues I tried the following:

`	var entity = document.querySelector('[sound]');

	AFRAME.registerComponent('markerhandler', {
	   tick:function() {
	      if(document.querySelector("a-marker").object3D.visible == true) {
	      // MARKER IS PRESENT
				entity.components.sound.playSound();
	      } else {
	      // MARKER IS HIDDEN
				entity.components.sound.pauseSound();
	      }
	   }
	});
`

With the scene being:
```
    <a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;';>
	  	<a-marker preset="hiro">
	            <a-box position='0 0.5 0' material='color: black;'></a-box>
	  	</a-marker>
  	  	<a-assets>
    		<audio id="sound" src="audio.mp3" preload="auto"></audio>
  		</a-assets>
  	<a-entity sound="src: #sound" autoplay="false"></a-entity>
  	<a-entity camera></a-entity>
    </a-scene>
```
Doesn't seem to register. Any ideas as to why?

**Comment by donmccurdy** [comment]
This seems like a workaround to https://github.com/jeromeetienne/AR.js/issues/217 and not related to aframe-extras, I think you will need to follow up there. I do not use AR.js myself.
