### ISSUE TITLE
Camera rotation resets after I release right gamepad joystick

### ISSUE THREAD

**Issue by js-d-coder** [c-frame/aframe-extras#229]
Hi,
I am using aframe-extras v4.0.3, Aframe 0.8.2 and have tested it on Chrome 66, Firefox 59, Edge 41 on Windows 8 and Ubuntu using Red Gear gamepad.
The problem is camera rotation resets to `0 0 0` after I release the joystick. It rotates well while I have joystick pressed in any direction.  
I am using `movement-controls` component on rig with camera as its child as:

```
<a-entity id="rig" movement-controls>
  <a-camera position="0 1.6 0" >
    <a-entity cursor position="0 0 -1" geometry="primitive: ring; radiusInner: 0.02; radiusOuter: 0.03" material="color: black; shader: flat"></a-entity>
  </a-camera>
</a-entity>
```
Test code https://pastebin.com/TfVUJBP5  
Thanks (sorry for a lot of bug reports recently)

**Comment by dsinni** [comment]
Having this same issue in all versions of `4.*.*` with a gamepad. So far only texted with Xbox 360 controller. Mouse and keyboard seem to work fine.

There's another issue (#234) where you can basically roll your head between your legs and back around again. Haha. I'd like to see that in 3rd person. I'm not sure if that's related.

Both of these issues can be seen here: https://codepen.io/dansinni/pen/odLKMQ

Thanks, and keep up the excellent work, @donmccurdy. You're a beast.
