### ISSUE TITLE
Player keeps moving when using movementEnabled: false

### ISSUE THREAD

**Issue by bnolan** [c-frame/aframe-extras#23]
When using an element like:

```
<a-entity camera kinematic-body />
```

And I programmatically set

```
setAttribute('universal-controls', 'movementEnabled: false')
```

The player keeps rolling at the speed it was travelling before. You have to stop the player completely before disabling movement. It'd be better if the player rolled to a stop even if you have movementEnabled set to false.

**Comment by donmccurdy** [comment]
Thanks! Yeah I agree decelerating but ignoring new input seems best.
