### ISSUE TITLE
Error in nav-mesh component for large meshes 

### ISSUE THREAD

**Issue by rmrbytes** [c-frame/aframe-extras#233]
I find when the boundary of the nav-mesh is very large (around 200 mts x 200 mts), an error is throwing up.

```
Uncaught TypeError: Cannot read property '4' of undefined
    at Path.clampStep (aframe-extras.js:6036)
    at o.clampStep (aframe-extras.js:8800)
    at i.<anonymous> (aframe-extras.js:7076)
    at HTMLElement.value (a-scene.js:593)
    at HTMLElement.value (a-scene.js:641)
    at bind.js:12
    at y (three.js:21940)
```

The nav-mesh is being created via a custom geometry by passing coordinates of the vertices. The mesh itself is a simple T shape. The coordinates of the vertices (clockwise) in the example is:

`-5.75 0 0.1, -5.75 0 -148, -150 0 -148, -150 0 -160, 54 0 -160, 54 0 -148, 5.75 0 -148, 5.75 0 0.1`

The geometry creates a number of triangles and they seem to be correct. I have been using several meshes of smaller sizes and it has never thrown this error.

If it helps to create the layout in glitch I can do so

**Comment by donmccurdy** [comment]
Yes a demo would be helpful, thanks. I don't think the size you show here should be any problem by itself.

**Comment by donmccurdy** [comment]
Ahh ok I see the issue now, thanks the demo helps 👍

**Comment by rmrbytes** [comment]
Thanks
