### ISSUE TITLE
`movement-controls` allows camera pitch to rotate 360+ degrees with gamepad

### ISSUE THREAD

**Issue by dsinni** [c-frame/aframe-extras#234]
When using a gamepad, `movement-controls` allows the camera pitch to complete a full 360+ degree rotation. It does not stop while looking straight up or down as it does with other controls.

Seems to be happening in all versions of `4.*.*`.

Bug reproduced in various browsers on Windows 10 with an Xbox 360 controller.

Issue can be seen here: https://codepen.io/dansinni/pen/odLKMQ

**Comment by donmccurdy** [comment]
Fixed in  b488e66, coming with next release.
