### ISSUE TITLE
What is the proper way to make movement-controls orient in the direction of pointing?

### ISSUE THREAD

**Issue by dritsher** [c-frame/aframe-extras#235]
I have tried:
```
<a-entity id="rig"
          movement-controls="fly: true; camera: [hand: left]">
```

But this is not working.  I am not sure if I am referencing improperly, or if camara can only be a camera.

Is it possible to set the orientation of movement-controls to something other than the active camera?

**Comment by donmccurdy** [comment]
It's just a CSS selector, so if your HTML is `<a-entity hand id="left" />` then it should be either of the following:

```
camera: [hand]#left

camera: #left
```

> EDIT: Oh i see, `hand` isn't a component... probably just want to add an ID then. Haven't tested this with non-camera orientation elements yet though.

**Comment by dritsher** [comment]
Thank you.

`camera: #left`

This works properly
