### ISSUE TITLE
halt movement of navigation by status in nav-mesh

### ISSUE THREAD

**Issue by rmrbytes** [c-frame/aframe-extras#236]
The `movement-controls` with `nav-mesh` is a convenient way for the user to navigate along a specified path. However, if the application scene demands a change of state of the user, say to a **restful** (assume user is sitting at a location) state, then there should be a way to halt the movement even when using keys by setting movement status to false. And perhaps resetting it to true by some event. This could be perhaps done in movement-controls

**Comment by donmccurdy** [comment]
Newish docs here: https://github.com/donmccurdy/aframe-extras/tree/master/src/controls#options, you can do movement-controls="enabled: false" and rotation should continue working.

**Comment by rmrbytes** [comment]
Oh. but of course. My bad.
