### ISSUE TITLE
on mouse click cursor disappearing issue with version 3.8.6

### ISSUE THREAD

**Issue by rohitkshirsagar** [c-frame/aframe-extras#239]
Hi,
I am using https://cdn.rawgit.com/donmccurdy/aframe-extras/v3.8.6/dist/aframe-extras.min.js aframe extra version **3.8.6** with aframe version **0.6.0** , on mouse clicked cursor is disappearing, need to pressed esc key everytime to get cursor back.
can someone please help me into this issue.

**Comment by donmccurdy** [comment]
This feature is called "pointer lock", and you can disable it with:

```
<a-entity camera universal-controls mouse-controls="pointerlockEnabled: false"></a-entity>
```

**Comment by donmccurdy** [comment]
Sure thing!
