### ISSUE TITLE
movement-controls: "TypeError: nav is undefined"

### ISSUE THREAD

**Issue by twastvedt** [c-frame/aframe-extras#245]
When loading my scene using movement-controls I get the error "TypeError: nav is undefined" on [line 60](https://github.com/donmccurdy/aframe-extras/blob/master/src/controls/movement-controls.js#L60) of movement-controls because `el.sceneEl.systems.nav` is undefined. If I modify line 57 to be:
<pre>    if (data.constrainToNavMesh !== prevData.constrainToNavMesh <b>&& el.sceneEl.systems.nav !== undefined</b>) {</pre>
then everything works just fine. It looks like a bug, but am I missing something? It seems like plenty of others must have tried using movement-controls without nav meshes.

**Comment by donmccurdy** [comment]
Hm I see, are you using just the controls part of the package and leaving the rest out of your app? e.g. `aframe-extras.controls.min.js`?  I probably need to test for that case.

**Comment by donmccurdy** [comment]
It’s supposed to be supported, so yeah I think it’s just a mistake here. Will look into it in a few days or feel free to open a PR. ☺️

**Comment by twastvedt** [comment]
OK, cool. Thanks! I'm happy to open a PR with the above single line change if that would be useful, but I'm not sure what a proper fix would involve if you're imagining something more involved.
