### ISSUE TITLE
a-tube: radialSegments don't work

### ISSUE THREAD

**Issue by jhadenfeldt** [c-frame/aframe-extras#248]
The settings for `radialSegments` are ignored, while `segments`, `radius` and `path` are working fine. 

Here is an example: https://jsfiddle.net/2oxcd5Le/

The cause seems to be the camelCase for the attribute. Changing the attribute name from `radialSegments` to `radialsegments` within the component fixes the issue: https://jsfiddle.net/8fagop69/

**Comment by donmccurdy** [comment]
Fixed in https://github.com/donmccurdy/aframe-extras/commit/f3cf96cc38baa24a41bf60b59f4adec556397645
