### ISSUE TITLE
Feature\Checkpoint-keyboard-controls

### ISSUE THREAD

**Issue by LukeTOBrien** [c-frame/aframe-extras#250]
Hello there,

I have recently stumbled upon A-Frame and the extras, I like what I see and I think the potential is rather exciting.  
I have been pondering combining the checkpoints and keyboard controls.  
This would work in the following way:

* Keys would mapped via properties to control progression to the next/previous checkpoints (default right and left arrow keys).
  * We would have to keep track of the current checkpoint.

The thing I'm thinking about is movement similar to [slideshow-component](https://www.npmjs.com/package/aframe-slideshow-component).  
So you could go from scene to scene in a slideshow kinda way.

I have also been thinking that a timer could also be added, so the camera could automatically move through the checkpoints and spend a certain interval at each scene.  
So, taken your checkpoints example, the markup would be: (Where the time here is minutes)

```html
      <!-- Checkpoints -->
      <a-entity position="1 0 1">
        <a-cylinder checkpoint="interval:3" radius="1" height="0.1" position="0 0 -5.2" color="#39BB82"></a-cylinder>
        <a-cylinder checkpoint="interval:5" radius="1" height="0.1" position="3 0 0" color="#39BB82"></a-cylinder>
        <a-cylinder checkpoint="interval:4" radius="1" height="0.1" position="-3 0 0" color="#39BB82"></a-cylinder>
      </a-entity>
```

This would mean that the camera spends 3 minutes on the first checkpoint, then moves to the next, spends 5 minutes here, move to next, spends 4 minutes here.... then optionally repeats.  
I think arrow keys could still be useful here, allowing the user to go back.

What do you think of this idea?  
I'm afraid that I might not be able to contribute to the code itself as I might not have the time, but I've contributed the idea at least ;-)

**Comment by donmccurdy** [comment]
Hi! You can set this up in your application's code by putting IDs on the checkpoints and doing something like...

```js
var el1 = document.querySelector('#checkpoint1');
var el2 = document.querySelector('#checkpoint2');
setTimeout(() => el1.components.checkpoint.fire(), 30 * 1000);
setTimeout(() => el2.components.checkpoint.fire(), 60 * 1000);
...
```

Since it's not too complex to build into the app, I don't think it makes sense to put into aframe-extras directly, but hopefully that gets you started!
