### ISSUE TITLE
universal-controls orientation on mobile

### ISSUE THREAD

**Issue by LitMB** [c-frame/aframe-extras#251]
Good morning,
using a smartphone and a bluetooth gamepad, what is the proper way 
to make  movement orientation in the direction of camera
in a mobile environment ? I tried putting a camera inside a rig, but 
movements are always oriented to the latter instead of look.

Thanks

**Comment by donmccurdy** [comment]
What version of aframe and aframe-extras are you using? Note that for aframe 0.8 and latest extras, `universal-controls` has been replaced by `movement-controls`: 

https://github.com/donmccurdy/aframe-extras/tree/master/src/controls

But movement with a gamepad should still work, using the examples there.

**Comment by LitMB** [comment]
Excuse me, I realized that I used a wrong version of aframe with aframe extras.
Now it works, thanks.

Great library !
