### ISSUE TITLE
Controls speed issue

### ISSUE THREAD

**Issue by paussus** [c-frame/aframe-extras#254]
Hi,
  I have a problem with the controls speed because when the framerate is low it moves faster. At least when using keyboard controls and contrained to a navigation mesh. I think the issue is that velocity is multiplied twice by the delta. 

[At updateVelocity()](https://github.com/donmccurdy/aframe-extras/blob/master/src/controls/movement-controls.js#L208):
`          vector2.setLength(factor * this.data.speed * dt);`

[And later at tick()](https://github.com/donmccurdy/aframe-extras/blob/master/src/controls/movement-controls.js#L118):
`        end
          .copy(velocity)
          .multiplyScalar(dt / 1000)
          .add(start);`

If I replace the dt in updateVelocity() by a constant I get the same speed independently of the framerate.

Thanks!
Pau

**Comment by donmccurdy** [comment]
Thanks, and sorry for the late reply — would you be able to open a PR?

**Comment by donmccurdy** [comment]
Merged #267
