### ISSUE TITLE
Keyboard controls speed

### ISSUE THREAD

**Issue by paussus** [c-frame/aframe-extras#255]
Hi,
  when using keyboard controls and moving in diagonal by pressing two keys of different axis the resulting dVelociy vector has a length of 1.414 while if you move in straight line the length is 1 ([code](https://github.com/donmccurdy/aframe-extras/blob/master/src/controls/keyboard-controls.js#L58)). So you effectively move faster than the defined speed, it's not a big deal and I'm not sure, but shouldn't it be normalised?

Thanks
Pau

**Comment by donmccurdy** [comment]
Yeah I think you're right, thanks — this should be normalized.

**Comment by paussus** [comment]
Thanks to you!

**Comment by donmccurdy** [comment]
Merged #267
