### ISSUE TITLE
FBX loader with separate animation FBX files

### ISSUE THREAD

**Issue by rmrbytes** [c-frame/aframe-extras#257]
Many of the FBX based models store their animations in separate files. This is especially true for humanoids where most of the modellers use the Mixamo animations. One way out of this is to import the relevant files to Blender and then export to glTF. However, most of the assets (especially from Unity store) give the FBX as ASCII and Blender throws an error.

The request is: would it make sense to add a separate property in FBX Loader component, where besides the `src` we can specify an array of `animations` files?

**Comment by donmccurdy** [comment]
I looked into this a while ago and wrote up my results here: https://github.com/donmccurdy/aframe-extras/issues/147. tl;dr it's technically possible, but mostly a headache, and with Mixamo in particular I didn't get anywhere. Note the `feat-mixamo` branch mentioned in the issue, and the [fbx-animation](https://github.com/donmccurdy/aframe-extras/blob/feat-mixamo/src/loaders/fbx-animation.js) component within it.

I gave up on that; I've had better success with glTF, and the [Mixamo -> glTF workflow](https://www.donmccurdy.com/2017/11/06/creating-animated-gltf-characters-with-mixamo-and-blender/) isn't bad. But feel free to use any information in that thread if it's helpful to you.

Also note, you may be able to export glTF files directly from Unity with https://github.com/KhronosGroup/UnityGLTF.

**Comment by rmrbytes** [comment]
Thanks Don. I thought of just sounding you ... only because there is a huge
asset base in Unity for many of us to thrive on. Will follow the workflow
you have suggested on the best way out. Also am exploring an easy way to
have the FBX from the asset store in binary.
