### ISSUE TITLE
Keep Movement Controls (WASD or Controller or Touch) in headset

### ISSUE THREAD

**Issue by TheBiggestNumber** [c-frame/aframe-extras#258]
Hi,

WASD, Controller and Touch Movement Controls get disabled when entering VR headset mode.

Is there a way to keep these movement controls active in the headset?

Thanks!

**Comment by donmccurdy** [comment]
See https://github.com/donmccurdy/aframe-extras/blob/master/src/controls/README.md - you’ll need to have an entity (“camera rig”) wrapping the camera.
