### ISSUE TITLE
Rig rotation in movement-controls.js

### ISSUE THREAD

**Issue by jvraines** [c-frame/aframe-extras#260]
Any plans to work on rotation as noted by the TODO at Line 191? The nav mesh works great for me and I'd hate to give it up, but I need an initial rotation on my camera. If I put a rotation component on the camera element, it's ignored. If I put it on the rig instead, then my keyboard movement is skewed.

**Comment by donmccurdy** [comment]
Yes, I consider it a bug that this doesn't work already. But I haven't had the chance to fix the math there yet. PRs would be welcome. :)
