### ISSUE TITLE
can we programmatically move using emit

### ISSUE THREAD

**Issue by rmrbytes** [c-frame/aframe-extras#272]
Is it possible to move (using `movement-controls` the user (camera) either by some increment (say 1 m) or to an absolute position (kind of like teleporting but a very small distance say 1 m) in some manner using some emit? This is using `nav-mesh` constraint. Such a need may arise as part of some other gesture (click on an object) that the user may do. Thanks

**Comment by donmccurdy** [comment]
Affecting movement-controls with events isn't supported, although you can certainly move the rig around using components like `event-set`. If you want to move the rig and have that respect nav-mesh constraints, you would need to write a custom controls component that "plugs into" the `movement-controls` system. This can be fairly simple (e.g. listen for an event) and will automatically get nav-mesh constraints applied. See: https://github.com/donmccurdy/aframe-extras/tree/master/src/controls#customizing-movement-controls

In this case you'd register your plugin component like:

```html
<a-entity id="rig" movement-controls="controls: gamepad, keyboard, touch, custom;">
  <a-entity camera ...
```

**Comment by rmrbytes** [comment]
Thanks @donmccurdy . Will give `event-set` a shot before trying out a custom-control.

**Comment by rmrbytes** [comment]
@donmccurdy : Related to this is my need is to (customise) **animate** the movement when a user via the keyboard keys or via the emit moves the rig. What I am building is a Robot (like an R2D2 as an avatar) that moves around using nav-mesh constraints (that is important to my need). Now, for every key forward press, I need to trigger a set of hinge based rotations and translations (as per robot elements) to move forward. This combination of rotations and translational movements based on the robot design is simple physics for a given desired distance. What I am trying to understand is: how do I coordinate the timings of the animation to match that of `movement-controls` and (b) how do I get the distance that the robot must move. My assumption is that I will have to make a custom control overriding some of the functions of the base control  component. Any advise will be helpful. Thanks

**Comment by donmccurdy** [comment]
Your custom component will be able to determine the speed that the robot moves, or you can choose a `speed` property on the `movement-controls` component. But yes your code would need to manage the animation, and I don't have a good answer for you there... the three.js forum may be worth a try? You could also look for tutorials about creating a "walk cycle" in tools like Blender. If you can export a few basic animations (walk, strafe left, strafe right) you can fade between them more easily than managing individual joints.

**Comment by rmrbytes** [comment]
Thanks @donmccurdy . But that would mean that the animations within the model would have to match (on duration) with the speed of the custom component, right? Hence, lets say the user presses the up key to move the avatar forward,  the animation would have to be completed within the same time because the change in position of the rig would be done by the custom movement-controls. Am I right?

Will check the approach you are suggesting.

**Comment by rmrbytes** [comment]
Oh. ok. That gives me enough fodder to pursue. Thanks @donmccurdy. Will hopefully find a way
