### ISSUE TITLE
About displaying distorted objects

### ISSUE THREAD

**Issue by mozgbrasil** [c-frame/aframe-extras#273]
Hello good afternoon

About displaying distorted objects

I'm trying to simulate the example "water"

https://webvr.donmccurdy.com/water/

But in the use of the library "aframe-extras.min.js" which is pointed out in its reposition of the github see, which is displaying the distorted objects

https://codepen.io/mozgbrasil/pen/yRbMvM

**Comment by donmccurdy** [comment]
Hi, I'm not sure what you're asking sorry. The Codepen example shows the ocean correctly for me.

If you're trying to raise the camera above the ocean and let the user look around, recent versions of A-Frame and this library work differently. See https://github.com/donmccurdy/aframe-extras/tree/master/src/controls, or:

```html
<a-entity id="rig" movement-controls>
  <a-entity camera
            position="0 1.6 0"
            look-controls="pointerLockEnabled: true"></a-entity>
</a-entity>
```

**Comment by arpu** [comment]
you need set a entity around the camera and set the position
this should working (in your example you are under the water)
https://codepen.io/anon/pen/yRbpdo

**Comment by mozgbrasil** [comment]
Thank you my friend, it worked as expected.
