### ISSUE TITLE
Is there a way to use two locomotion methods together? (keyboard and checkpoint)

### ISSUE THREAD

**Issue by mzpq01** [c-frame/aframe-extras#274]
I am wondering if there is a way to do the following:
In a desktop mouse control vr situation, if I want user to simultaneously use wasd keyboard controls and checkpoint control, while also be limited in the nav-mesh area which is defined by "constrainToNavMesh". Like shown in the pic. But when I tried this, the navmesh is not constraining the movement anymore, and when I clicked the checkpoint, it has a offset to the desired checkpoint position. Am I doing something wrong? I applied the checkpoint point component to a cylinder primitive.
![2018-10-18_09-50-47-cc787e6e652c5cb9280133dab86fc4a2](https://user-images.githubusercontent.com/17068462/47161455-a8424980-d324-11e8-85c0-a023c54163d6.png)
Thanks!
Xu

**Comment by donmccurdy** [comment]
If you want to allow both WASD and checkpoint controls you'll need to list them both:

```html
<a-entity movement-controls="speed: 0.15;
                             constrainToNavMesh: true;
                             controls: gamepad, keyboard, touch, checkpoint;">
...
```

>  it has a offset to the desired checkpoint position

i'm not sure about this part — can you share more of the scene? It could be a bug if your checkpoint is nested under other entities with different offsets.

**Comment by mzpq01** [comment]
Ah...It works now! I do not know why I cannot repeat the offset movement. But I found that if I put the checkpoint on the other side of navmesh obstacle but visible and clickable, when I click the checkpoint, it moves through navmesh. Did you intentionally make it penetrable like that? And I also see an example here that the developer used kinematic-body to limit the movement rather than nav-mesh and the performance is ok

http://vr.jadedalloul.com/

In your doc, you said kinematic-body is not recommended, but here I can see a good example of using it instead of nav-mesh, and the kinematic-body component can also work on imported model right? Thanks for your explanation!

> If you want to allow both WASD and checkpoint controls you'll need to list them both:
> 
> ```
> <a-entity movement-controls="speed: 0.15;
>                              constrainToNavMesh: true;
>                              controls: gamepad, keyboard, touch, checkpoint;">
> ...
> ```
> 
> > it has a offset to the desired checkpoint position
> 
> i'm not sure about this part — can you share more of the scene? It could be a bug if your checkpoint is nested under other entities with different offsets.

**Comment by donmccurdy** [comment]
I’d be glad to have checkpoint-controls support a navigation mesh, but currently you’re right that it does not. 

I don’t know if kinematic-body would work here or not, definitely checkpoint-controls does not use physics though. Feel free to try but I’m more interested in fixing navmesh issues than kinematic-body issues generally. :)

**Comment by donmccurdy** [comment]
Tracking this in https://github.com/donmccurdy/aframe-extras/issues/281.
