### ISSUE TITLE
Checkpoint speed issue

### ISSUE THREAD

**Issue by martinlieboe** [c-frame/aframe-extras#277]
It might be me just noobing out completely, but adding speed in the movement-controls does not seem to do anything. Have i just misunderstood? Any help is much appreciated. 
here is how i wrote it: (hoping i just did it wrong) 

![image](https://user-images.githubusercontent.com/44893138/48254173-8d399580-e409-11e8-893a-0597ddba8de1.png)

**Comment by donmccurdy** [comment]
Which version of extras are you using?

**Comment by donmccurdy** [comment]
This should have been fixed in a recent version of aframe-extras. If not, a demo would help mo to debug this. Thanks!
