### ISSUE TITLE
animation-mixer duration ignored in 4.2.0

### ISSUE THREAD

**Issue by florentpeyrard** [c-frame/aframe-extras#278]
Hi @donmccurdy ,

I'm seeing a regression using these parameters :` loop: once; duration: 20; clip:Standup;crossFadeDuration:0`. The duration is ignored, the clip is played with base duration.

I had to revert to 4.0.3 to get back the correct behavior. Aframe v0.8.2.

**Comment by donmccurdy** [comment]
Hm, I think the only recent change was https://github.com/donmccurdy/aframe-extras/commit/3ce78e662393c5a29462f151f94a00656acc6b73, and it's not obvious why that should break duration. Would you be able to share a demo?

**Comment by donmccurdy** [comment]
Found the issue, thanks. This will be fixed in the next release. Meanwhile you can also use the `timeScale` property to get the same effect.

**Comment by florentpeyrard** [comment]
Ok, thanks for the good news :)
