### ISSUE TITLE
Publish examples on github.io

### ISSUE THREAD

**Issue by RangerMauve** [c-frame/aframe-extras#28]
It'd be nice to be able to view them and show them as references without having to clone and build them locally first.

**Comment by donmccurdy** [comment]
I should add a link somewhere (and more docs in general) but most are here: https://sandbox.donmccurdy.com/vr/

**Comment by RangerMauve** [comment]
Ah, yeah, a link would be good.

**Comment by RangerMauve** [comment]
I was mostly interested in the shadows, however. :O

**Comment by donmccurdy** [comment]
Ok! Added the link – haven't put the shadows demo up yet because there have been some performance issues.

**Comment by RangerMauve** [comment]
Nice. :D
