### ISSUE TITLE
[animation-mixer] Document additional properties

### ISSUE THREAD

**Issue by donmccurdy** [c-frame/aframe-extras#284]
Forgot to document clampWhenFinished, maybe others.

**Comment by agoldev** [comment]
Hey, just wondering if you're aware of any examples of using clampWhenFinished? I'd like to use it for freezing a gltf animation clip on the last frame. Thanks!

**Comment by donmccurdy** [comment]
Is `animation-mixer="clip: *; clampWhenFinished: true"` not working? It should do exactly what you describe.
