### ISSUE TITLE
a-link not working with movement-controls

### ISSUE THREAD

**Issue by LukeTOBrien** [c-frame/aframe-extras#289]
A-Frame: 0.8.2  
Extras: 5.0.1

Hello,

I have a scene where the camera is controlled with your `movement-control`, the scene contains `a-link`, but the click event isn't working on it as expecting, I expect something like the [link traversal showcase](file:///C:/Repositories/aframe/examples/showcase/link-traversal/index.html)

I suspect this is not working because the camera is tracked to the mouse and capture mouse move, as opposed to the showcase when only mouse drag moves the camera.

Would it be possible to make the `a-link` component work with `movement-controls`.

Thanks

(I also found that updating to 5.0.1 also broke  *jump ability* for me, I may revert to 4.1.2 I was using previously)

**Comment by dsinni** [comment]
@LukeTOBrien Re: `jump-ability`

Pretty sure you now have to add `kinematic-body="enableJumps: true;"`.

I believe this was added to mitigate stability issues (camera bouncing) by default.

**Comment by LukeTOBrien** [comment]
Ahh yes that works thank you.

About the link thing, do you think we could detect the camera's proximity to the link?  
So focuses and moves up to a link, it glows, then when the user enters the link, it navigates.  

What do you think?

**Comment by donmccurdy** [comment]
Could you provide a demo or example? Are you putting `movement-controls` on a wrapper entity around the camera, as shown here? https://github.com/donmccurdy/aframe-extras/tree/master/src/controls#usage

This sounds like a bug in `a-link` to me; it tries to detect the world position of the camera but maybe there's an issue there.

**Comment by donmccurdy** [comment]
For click events to work you'll need to have a cursor as well. For example:

```html
      <!-- Player -->
      <a-entity id="rig"
                movement-controls
                position="0 0 0">
        <a-entity id="camera"
                  camera
                  position="0 2 0"
                  look-controls="pointerLockEnabled: true">
           <a-cursor></a-cursor>
        </a-entity>
</a-entity>
```

As far as detecting proximity to the link, that would be a feature request for the `link` component rather than `movement-controls` probably.

**Comment by LukeTOBrien** [comment]
Thanks, I will close this
