### ISSUE TITLE
Collision box on a obj model is much too big

### ISSUE THREAD

**Issue by bnolan** [c-frame/aframe-extras#30]
I'm putting the [attached model](https://github.com/donmccurdy/aframe-extras/files/244305/bakelite.obj.zip) in my scene and the physics model is much bigger than the model. I'm guessing I'm doing something wrong? I've enabled physics debugging.

<img width="764" alt="screen shot 2016-05-01 at 1 26 33 pm" src="https://cloud.githubusercontent.com/assets/17499/14944168/6c130228-0fa0-11e6-8589-6f61ee29e6b4.png">

**Comment by donmccurdy** [comment]
This should be fixed up now, as of d100622f6597b502c9260d60d7593c56fe984b82 and v1.13.0
