### ISSUE TITLE
How to embed Extra-Laoders in my case object-model.js into my angular project (index.html)?

### ISSUE THREAD

**Issue by s181173** [c-frame/aframe-extras#300]
Hey guys, 
I'm currently studying Business Informatics and my task is to build an AR-Web Viewer. My company exports JSON-Models, therefore I would need to embed the Extra-Loader. What I already tried:

 <script src="https://aframe.io/releases/0.9.1/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.7.1/aframe/build/aframe-ar.js"></script>
<script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
<script>THREEx.ArToolkitContext.baseURL = 'https://rawgit.com/jeromeetienne/ar.js/master/three.js/'</script>

<body style='margin : 0px; overflow: hidden;'>
<a-scene embedded arjs =’sourceType: webcam;’>
  <a-marker preset = "hiro">
    <a-entity
    json-model=”src:url(assets/nike-model/nike.json);” scale = "100 100 100" >
    </a-entity>
 </a-marker>
 <a-entity camera>
 </a-entity>
</a-scene>
</body>

I would use the general Extra-Loaders and not the specific one for JSON-Models if possible. There's no error but the model is not loading no matter which scale I use, GLTF and OBJ are working, so would glad if anyone can help me how to use the Extra-Loaders step by step.
Thanks in forward

**Comment by donmccurdy** [comment]
> I would use the general Extra-Loaders and not the specific one for JSON-Models if possible. 

I'm not sure what you mean by this...

Are you sure the JSON your company is exporting is using the three.js JSON format? Not all `.json` files are compatible with `object-model`, pretty much anything can be put into a JSON file, so you have to be careful there. If you could create a demo that uses _just_ A-Frame and A-Frame Extras (without AR.js for now) that would be much easier to debug.

**Comment by s181173** [comment]
I tried this here:
<script src="//cdn.rawgit.com/donmccurdy/aframe-extras/v6.0.0/dist/aframe-extras.min.js"></script>
so only integrating this url without downloading the package, but I also tried to download the repo and embed it locally, like this:
<script src = "assets/loaders/object-model.js"> </script>
And also tried this url:
<script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>

the last trial was due to this guy: https://medium.com/@akashkuttappa/using-3d-models-with-ar-js-and-a-frame-84d462efe498 and this is what I meant, he integrates all loaders, so not only object-model, in my case the loader object-model.js would be enough I guess, cause my company only export json-files.

How I try to embed the json model:
https://medium.com/@akashkuttappa/using-3d-models-with-ar-js-and-a-frame-84d462efe498 (got the code for the model from here)

I got this model from here so actuallly it should work:
https://clara.io/library

None of my trials is working, so I tried different scales but the model is not depicted. If you could tell me, what I'm doing wrong, I would be very thankful. So I received no error btw, but the model is just not visible.

**Comment by donmccurdy** [comment]
Please start by creating a live demo using either all of aframe-extras, or just the loaders. Once you have that working, then you can figure out how to extract only the loader you want. 

I'm not going to set up a demo myself using all of the technology you are using, so you'll need to create a live demo reproducing this issue, ideally as simply as possible, for me to debug it.
