### ISSUE TITLE
[Question] Make movement-controls touch-controls. camera touch-move by y-axis  

### ISSUE THREAD

**Issue by konstantin55000** [c-frame/aframe-extras#302]
Hello, have been checked
https://github.com/donmccurdy/aframe-extras/blob/master/src/controls/movement-controls.js
but have not found touch movement on y axis,

alswo've checked example in doc, how to make custom controls, 
but not undertand so far.
Could you please give basic example how to make touch controls on devices. 
so, camera should be roatate not only on x axis, but also on y axis (down and up)
something, for example

```<a-entity id="rig" movement-controls="touch>
  <a-entity camera
            position="0 1.6 0"
            look-controls="controls: touch; pointerLockEnabled: false">
  </a-entity>
</a-entity>``` . 

Also do i need some place to make override, like
let vector3 = new THREE.Vector3();
...
 vector3.set(dVelocity.x, dVelocity.y, dVelocity.z);

**Comment by donmccurdy** [comment]
All that the `touch-controls` component does is let you tap the screen to move forward – see the [controls documentation](https://github.com/donmccurdy/aframe-extras/tree/master/src/controls#controls) for more information here. It doesn't rotate the camera. That's a feature of A-Frame's builtin `look-controls`, but isn't currently a feature of `movement-controls`. Note that with this line in your example, you seem to be confusing the two:

```
look-controls="controls: touch; pointerLockEnabled: false
```

**Comment by konstantin55000** [comment]
Don, much thank you for clarification.
