### ISSUE TITLE
Playing an animation in reverse?

### ISSUE THREAD

**Issue by nsbingham** [c-frame/aframe-extras#303]
I'm attempting to play an animation defined in a GLB in reverse using `animation-mixer`. 

I use this code to trigger the animation, which works as expected.

```
obj.setAttribute('animation-mixer', {
     clip: "Grow",
     loop: "once",
     clampWhenFinished: "true"
});
```

Later, I attempt to play the animation in reverse on the same object with the following code:

```
obj.setAttribute('animation-mixer', {
     clip: "Grow",
     loop: "once",
     clampWhenFinished: "false",
      timeScale: "-1"
});
```

My expectation is that the animation would play in reverse, but nothing appears to happen. If I log `obj.getAttribute('animation-mixer')`, I see the updated values.

**Comment by netgfx** [comment]
I would be interested in this as well, is this supported or somehow doable?

**Comment by netgfx** [comment]
@nsbingham I have achieved this by doing: `clip: Walk; timeScale: -1; clampWhenFinished:true; repetitions:1;`

**Comment by vincentfretin** [comment]
It seems the same issue as #364. I'm closing this issue as duplicate.
