### ISSUE TITLE
[movement-controls]: Lost Orientation on Fly Toggle

### ISSUE THREAD

**Issue by jon-lehman** [c-frame/aframe-extras#305]
Apologies if this has been brought up before. I've come to find an issue while toggling fly true/false programmatically while in-scene. If a user is in fly mode  `fly: true`, and they rotate their camera (or "head"), and toggle fly mode off `fly: false`, the controls become disoriented. By "disoriented", I mean that the W key will travel the user up (or sometimes down) on the Y-axis  and same with the S key. This also seems to be the case on mobile as well.

Steps to reproduce:
1. I setup an example scene here: [sample scene on glitch](https://glitch.com/edit/#!/testing-movement-controls), fire that up.
2. Toggle `fly: true` using the checkbox control in the upper left.
3. Fly around and angle your camera/head downward.
4. Now, toggle `fly: false` by unchecking the previous control.
5. Attempt moving around using keyboard controls, at this point it _should_ be "disoriented".

Current versions, browsers, and devices:
- aframe version: 0.9.2
- aframe-extras version: 6.0.1
- Desktop Browsers tested:
  - Chrome v78.0.3904.97
  - Firefox v70.0.1
  - Safari v13.0.2
- Mobile (iPhone Xr) Browsers tested:
  - Chrome v78.0.3904.84
  - Safari v13.2.2

Any help or insight into this issue would be much appreciated, thank you in advance.

**Comment by kylebakerio** [comment]
should be checked whether this still applies in 6.1.1 and 1.1.0

**Comment by kylebakerio** [comment]
the glitch link is dead, @jon-lehman

**Comment by vincentfretin** [comment]
The PR to fix this issue was merged.
