### ISSUE TITLE
[movement-controls]: No thumbstick locomotion in A-Frame 1.0.1+ in Oculus Quest

### ISSUE THREAD

**Issue by dsinni** [c-frame/aframe-extras#307]
It appears that locomotion using `movement-controls` (`6.0.1`) isn't currently working with A-Frame `1.0.1`+ in Oculus Quest.

It works pretty much as expected with `0.9.2` and `1.0.0`, with the occasional swapping of the left and right stick used for movement, which is perhaps a separate issue.

I unfortunately don't have a Quest to test with, but my colleague mentioned that he's experiencing this issue of not being able to move with either thumb stick in `1.0.1`+. It appears to work as expected in Rift S, so I'm thinking it's specific to either Quest or Oculus Browser.

My colleague confirmed that his firmware and Oculus Browser are up-to-date, so I believe we've ruled that out.

Code and demo can be found here: https://glitch.com/~slow-package
Direct link to demo: https://slow-package.glitch.me

Thanks for your attention to this. `movement-controls` is such a useful component. So much in fact, that I really believe it should be part of core. The absence of a solid solution for VR locomotion in core is probably one of A-Frame's bigger shortcomings.

**Comment by donmccurdy** [comment]
I'm not able to reproduce this. Testing:

- Device: Oculus Quest
- Browsers: Oculus Browser, Firefox Reality

Before entering VR mode, both browsers let me move with the trigger (emulating a screen press on mobile, I guess). After entering VR mode, the thumbstick works as expected. Is the issue just that the thumbstick doesn't work until you enter VR? Or is it not working in either case for your colleague?

**Comment by donmccurdy** [comment]
Well, that and the movement isn't oriented to the heading anymore... but that seems like a separate issue too.

**Comment by dsinni** [comment]
From what I understood, thumbstick was not working _in_ VR for A-Frame `1.0.1`+.

He reported that it _did_ work in `1.0.0`, but the sticks were reversed (right stick controlled movement).

Also, curious if your testing has been over `http` or `https`. Could it be that this would affect which API is used?

I'm hoping my colleague can chime in shortly to provide more info and possibly do some testing.

Thanks, @donmccurdy !

**Comment by donmccurdy** [comment]
My test was on HTTPS, your glitch demo and one of my own. But I haven't done much with the new WebXR API yet, could be that this makes a difference yes.

**Comment by dsinni** [comment]
Right on, @donmccurdy. Thanks for the feedback. Will keep you posted with what we can see on this end.

> 
> 
> Well, that and the movement isn't oriented to the heading anymore... but that seems like a separate issue too.

Ah. Interesting. I imagine that's a bit more difficult to use.

Last time I checked in Rift S, everything seemed to work fine, but I'll do another test there to see if I run into any of the same issues after any recent browser updates, etc. If I do, maybe I can help test.

Thanks again, Don.

**Comment by dsinni** [comment]
@DougReeder Not sure if you'd like to chime in at all on this since we were discussing it recently.

**Comment by gabrieljbaker** [comment]
Hi @donmccurdy , on Oculus Browser on Oculus Quest on https://slow-package.glitch.me/, I'm able to use trigger to move forward before entering VR mode, but as soon as I enter VR I can't move using the joystick.  I'll try on Firefox browser. 

And just FYI I'm on Oculus Browser version 7.1

**Comment by gabrieljbaker** [comment]
Following up on that ^ looks like on FireFox Mixed Reality browser, the left joystick does work for movement on that glitch, while on the Oculus Browser it still doesn't.... very strange. Do they have the same WebXR support I wonder? I thought the FF browser was still a bit behind on the webxr implementation.

**Comment by dsinni** [comment]
Just to also chime in here, I tested on Rift S again and it worked for me as expected in Firefox Official.

For some reason my Oculus app isn't currently letting me enter VR in Chrome or Firefox Developer Edition. That may be due to a Public Test Channel update, but it just started happening within the last week or so.

I was hoping to reproduce the issue so I could try to debug, but no dice, unfortunately.

**Comment by DougReeder** [comment]
For https://slow-package.glitch.me/ on Quest, in Firefox Reality (where WebXR is not yet supported, but WebVR is) locomotion works as expected: in flat mode, trigger, X or A button emulates a screen click and moves you forward.  In VR mode the left stick moves you around and the right stick does nothing.  In Oculus Browser, where WebXR *is* supported, flat mode works the same, but neither stick does anything in VR mode.

Each Oculus Touch controller has no gamepad and one joystick.  As detected by https://woolen-field.glitch.me/, under WebVR each Oculus Touch controller reports two axes, corresponding to the two axes of the joystick.   Under WebXR, each controller reports *four* axes to match the "xr-standard" controller mapping: https://immersive-web.github.io/webxr-gamepads-module/#xr-standard-gamepad-mapping.  The first two axes are always 0.0, and the joystick is reported on the third and fourth axes.

There does not currently appear to be any mechanism for the API to report that the first two axes are dummies.  We should probably report this scenario to the WebXR maintainers.

**Comment by donmccurdy** [comment]
Thanks @DougReeder! Ok, that makes sense. 

Yeah, I'd agree that knowing whether the device has a touchpad would be helpful here. Especially with the axes in order of importance, it's a bit surprising that a less important axis can be detected missing but a more important axis cannot.

I guess the workaround will be — if an "xr-standard" device reports a thumbstick, use it for movement and ignore the thumbpad (which we can't verify is there). I believe the existing logic will need to be kept for non-XR gamepads.

**Comment by DougReeder** [comment]
One possible algorithm for WebXR is to use the highest-numbered existing pair of axes, as they are guaranteed to be real: "Placeholder buttons and axes MUST be omitted if they are the last element in the array or all following elements are also placeholder buttons or axes."

**Comment by donmccurdy** [comment]
I don't think I'd want to make any assumptions about what `axes[index>=4]` might mean... there's also no guarantee the last two axes _are_ a pair, could be two independent single-axis knobs like on old flight controllers. 😅

**Comment by donmccurdy** [comment]
It was that, and...

> The Gamepad API states a snapshot of Gamepad data can be retrieved by calling the navigator.getGamepads() function. However, **Gamepad instances returned by an XRInputSource's gamepad attribute MUST NOT be included in the array returned by navigator.getGamepads()**.

... the code was only looking at `navigator.getGamepads()`. 

Just released `6.1.0` which should fix this particular issue. Not seeing the "movement isn't oriented to the heading" issue on Oculus Quest. Haven't done much further testing of aframe-extras on Quest / WebXR / A-Frame 1.0 so not guaranteed to be fully compatible yet.

**Comment by dsinni** [comment]
Awesome, @donmccurdy! Thanks so much for your attention on this.

From what I'm hearing, it's working as expected on Quest, more specifically Oculus Browser now. IIRC it was already working in Firefox Reality, probably due to lack of WebXR support?

Anyway, good stuff. Thanks again!

**Comment by DougReeder** [comment]
With 6.1.0, movement-controls now work under WebXR in Oculus Browser on the Quest (and still work under WebVR in Reality), but now it's the *right* joystick instead of the left under both APIs.  Not a big deal, but could confuse some people.

**Comment by donmccurdy** [comment]
^I don't think I've changed anything there, but it's probably been non-deterministic from the beginning. Wrote this code for single gamepads originally, so it just takes the first controller in the list (unless the index is overridden). Now that WebXR introduced left/right indicators it should be possible to improve that to not rely on indices, filed https://github.com/donmccurdy/aframe-extras/issues/313 to track.

**Comment by DougReeder** [comment]
Ah, hadn't realized that.

Thanks for the quick fix!
