### ISSUE TITLE
Trouble with animation-finished event

### ISSUE THREAD

**Issue by felipenmoura** [c-frame/aframe-extras#308]
The event `animation-finished` is being triggered multiple times during animation, then infinite times after it has finished!

I dynamically add an element (GLTF) with an animation and use `addEventListener('animation-finished')`. But the event is being triggered many times during the animation, and then, is triggered infinite times after it has finished!

I'm not sure what I could be doing wrong, or if this might be some kind of a bug/feature I'm missing! Could that be related to something weird in the GLTF model itself?!

**Comment by donmccurdy** [comment]
Could you share a demo to demonstrate the problem?

**Comment by felipenmoura** [comment]
Try this:

1) Access `https://ar-sebrae.on2.dev/`

2) Click ok, allow the camera, then click "Entendi"

3) Open the browsers console

4) Aim the webcam to the hiro marker and wait for the animation (a butterfly) to happen

You can see in the browser's console that the log is triggered multiple times. Some times, it was triggered the first time when it really finished, but then, triggered again a couple more times. In other moments, it triggers too earlier and then more times.

![image](https://user-images.githubusercontent.com/347387/72559594-ec076400-3883-11ea-86d4-488649f7cb69.png)

I also noticed some other animations I have trigger it differently as well.
You can see this happening using different markers, such as barcodes, like `1`, `2`, `4`, `5`, among others.

**Comment by donmccurdy** [comment]
I can't open that URL, sorry — "Server not available." Is that a local server?

If you're using an AR framework like AR.js, can you reproduce the problem without that? The marker is likely to introduce issues of its own, since the model sometimes flickers in-and-out as the marker registers. The components being shown and hidden can't necessarily detect that.

**Comment by felipenmoura** [comment]
Hmm, must have been some instability. It is public and I just accessed it!
Can you please try again?

**Comment by donmccurdy** [comment]
I looked up an image result for 'hiro marker' and tested with that. I'm seeing something like this in the logs:

<img width="405" alt="Screen Shot 2020-01-17 at 10 26 38 AM" src="https://user-images.githubusercontent.com/1848368/72636534-1a348480-3914-11ea-924d-d19e0edac8f4.png">

The marker seems to be found and lost regularly, and the 'animation-finished' event doesn't seem wrong given that? I may not be able to help you with this without a standalone example, without the AR stuff going on. I do not use Ar.js.
