### ISSUE TITLE
[movement-controls] doesn't work on Oculus Go since 1.0.1

### ISSUE THREAD

**Issue by evdem** [c-frame/aframe-extras#314]
Description: Camera movement-controls (by touchpad) don't work on Oculus Go since 1.0.1 but all works e.g. in my VR BOX 2 + Chrome + joystick.
A-Frame Version: > 1.0.0
Platform / Device: Oculus Go
Reproducible Code Snippet or URL:
```javascript
<script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script> 
<script src="https://cdn.jsdelivr.net/gh/donmccurdy/aframe-extras@v6.1.0/dist/aframe-extras.min.js"></script>
<a-scene>                                                              
  <a-entity id="rig"                                                   
            movement-controls="speed:0.1">                             
    <a-entity camera                                                   
              position="0 1.6 0"                                       
              look-controls="pointerLockEnabled: true">                
    </a-entity>                                                        
  </a-entity>                                                          
  <a-box position="0 1.5 -1" color="#777777" rotation="45 0 0"></a-box>
  <a-sky color="#484848"></a-sky>                                      
</a-scene>                                                             
```

**Comment by evdem** [comment]
1. Sorry, movement-controls work on Oculus Go in Firefox Reality.
2. Now I have to use A-Frame 1.0.4 on Oculus Go. Therefore controls don't work in Oculus browser e.g. in GLMol A-Frame port.
3. By using remote debugger I can get only
  init: function init() {
    console.log('touch init')
'touch init' console message yet. How shall I debug controls next?

**Comment by aitorgalo** [comment]
It's true it doens't works.

**Comment by blasco** [comment]
Any news on this? I can also confirm it still doesn't work

**Comment by samuel-zuk** [comment]
Can also confirm that movement-controls are broken on both the Oculus Browser and the Firefox Reality browser on my Oculus Go. Specifically, there is no motion with either the controller pad, clicking the pad, or pressing the button; however, the controller's touch pad rotates the camera. I get the feeling that this could be related to [this](https://github.com/n5ro/aframe-extras/issues/313), but more testing is required.

**Comment by vincentfretin** [comment]
I'm closing old issues, the issue may have been fixed in recent build, please try https://cdn.jsdelivr.net/gh/n5ro/aframe-extras@501d66b/dist/aframe-extras.min.js you can reopen if it's still an issue with aframe master and latest aframe-extras build.
Please note that both Oculus Go and Firefox Reality are unmaintained products now.
