### ISSUE TITLE
Question about ply loader

### ISSUE THREAD

**Issue by alromh87** [c-frame/aframe-extras#316]
Why was ply loader erased on d079064e6ac55a4cd6bbf64bd46a576e26dd214e?

**Comment by donmccurdy** [comment]
It's a rarely-used format, and I was no longer willing to maintain that part of the project. I would suggest converting models to another format like glTF instead.

**Comment by alromh87** [comment]
Thanks, tried it with latest aframe and works with no problem.

Took me some time to figure it out, since the only information I could find
was about using aframe-extras but it wasn't working. Even aframe
documentation references this project for ply.

**Comment by donmccurdy** [comment]
I'm not sure where the A-Frame docs mention that, but if you'd like to report an issue there please do!
