### ISSUE TITLE
No ../bundle.js found in examples/castle and examples/walls

### ISSUE THREAD

**Issue by cyber-hub** [c-frame/aframe-extras#317]
Guess you had camera movement in that ../bundle.js? But it no longer exists. 
Without it the examples are sadly nearly useless (in firefox, oculus, in chrome blank page).

**Comment by donmccurdy** [comment]
To run the examples locally you'll need to use either `npm run dev` or `npm run build`:

https://github.com/donmccurdy/aframe-extras/blob/fe293f78c815c07fefbb8eba36bccc41e126c2ff/package.json#L13-L14

The bundle file is generated from the source code, and essentially the same as the dist/ files.
