### ISSUE TITLE
interesting gamepad behaviour

### ISSUE THREAD

**Issue by coderofsalvation** [c-frame/aframe-extras#319]
So I have this bluetooth gamepad which seems to work fine in windows (steamVR) and android.
However, if I run the gamepad-controls in an aframe scene (chrome or firefox nightly) there seems to be some interesting mapping-issues happening (different issues per browser).

To be honest, I think this is rather a gamepad API-issue (browserspecific implementation) than an aframe-extras issue.
I was curious if somebody has ever created an aframe gamepad-mapping wizard e.g. as a workaround for gamepads which aren't behaving properly.

**Comment by donmccurdy** [comment]
Something like https://github.com/MozillaReality/gamepad-plus might handle it? It's not included in this project though, so I don't know whether it would fix your issue.
