### ISSUE TITLE
[cube-env-map] support for A-Frame cubemap syntax

### ISSUE THREAD

**Issue by kfarr** [c-frame/aframe-extras#323]
Digging into the rabbit hole of cube maps and A-Frame, I've found that each cubemap related component loads them differently.

However A-Frame supports a standard `a-cubemap` syntax using the asset loader, pasted here for convenience:
```
    <a-cubemap id="sky">
      <img src="right.png">
      <img src="left.png">
      <img src="top.png">
      <img src="bottom.png">
      <img src="front.png">
      <img src="back.png">
    </a-cubemap>
```

I think it would be useful to support this same syntax so that a selector can be used instead of a path with fixed file naming conventions.

Related ticket on another cubemap A-Frame repo:
https://github.com/bryik/aframe-cubemap-component/issues/14

Also I'll point out that the 8th wall team also modified this component because of this issue, they solved it *yet another way* (using default selectors for each side):
https://www.8thwall.com/8thwall/cubemap-aframe/master/

**Comment by donmccurdy** [comment]
Thanks – added a comment on https://github.com/bryik/aframe-cubemap-component/issues/14#issuecomment-627108994.
