### ISSUE TITLE
Oculus Go error last version (movement-controls)

### ISSUE THREAD

**Issue by aitorgalo** [c-frame/aframe-extras#324]
Hi,

Last version of aframe-extras (6.1.0)  doesn't work well with last version of a-frame (1.0.4) on Oculus Go with the class movement-controls.

The component starts but the camera adds 1.6 of Y position always. If I put Y=0 it starts at Y=1.6 and if I put on 1.6 it duplicates it.

Then when I use controls of Oculus Go it doens't moves on the plane, it rotates only the camera from 1 point.

I tried on last update of Oculus Go browser. 

There is an alternative way to make the camera moves when I press a button on controller?
I've read the documentation but I don't know where to move the camera on the code.

Thanks in advance.

**Comment by n5ro** [comment]
you can use teleport and left/right turn on your navigation stick as an alternative way to program movement into your app. I used the thumb controls component for starters

Thumb Controls
https://github.com/supermedium/superframe/tree/master/components/thumb-controls/

Teleport
https://github.com/fernandojsg/aframe-teleport-controls

Check out how movement works in a webxr page I published not that long ago. https://paigehorizon.glitch.me 

I will check on the aframe-extras bug that you are noticing. Unfortunately I no longer have an Oculus Go, I will try to borrow one.

**Comment by vincentfretin** [comment]
I'm closing old issues, the issue may have been fixed in recent build, please try https://cdn.jsdelivr.net/gh/n5ro/aframe-extras@501d66b/dist/aframe-extras.min.js you can reopen if it's still an issue with aframe master and latest aframe-extras build.
Please note that Oculus Go is an unmaintained product now.
