### ISSUE TITLE
very basic gamepad crashes when I touch left joystick

### ISSUE THREAD

**Issue by kylebakerio** [c-frame/aframe-extras#326]
error happens in line 190 of this file:
 https://github.com/donmccurdy/aframe-extras/blob/4371ffe9a6b747a941cd2f4a0f53cc97756ab7c6/src/controls/movement-controls.js

As soon as I touch left joystick, I see
`aframe-extras.min.js:1 Uncaught TypeError: Cannot read property 'object3D' of null`

Also, none of the other buttons do anything. Right joystick moves camera around in place, but that's it.

How can I get more usage from the controller? This is using 
`<a-entity id="player" camera networked="template:#avatar-template;attachTemplateToLocal:false;" movement-controls spawn-around-board="radius:1" position="0 .8 .4"></a-entity>
`

movement-controls (which I see in the code lists gamepad as its first default). When I use gamepad-controls like this, everything is the same EXCEPT no crash when touching left joystick.

Note that this is all without a 'rig' around the camera. If I add a rig, the right joystick does nothing, but there is also no crash.

I also noticed a crash when inspecting the scene and adding the keyboard controls after adding the gamepad controls, so it may have to do with that somehow?

Glad to help give more debugging info, not sure what's helpful since I don't know how it works.

**Comment by kylebakerio** [comment]
gamepad is: BBC-GAME (Vendor: 1949 Product: 0402)
and is correctly identified and shows correct inputs here:
https://html5gamepad.com/
Left joystick is axis 0/1

**Comment by donmccurdy** [comment]
See the [`movement-controls` docs](https://github.com/donmccurdy/aframe-extras/tree/master/src/controls#usage), a camera "rig" wrapping the camera element is strictly required. If you can share enough code to reproduce the "right joystick does nothing" issue I can look into that.

**Comment by kylebakerio** [comment]
Ok. I'll see if I can get a working demo built, I'm using a rig now. I'm using NAF, and realizing I need to network both the avatar, and separately create a template for the rig and network that as well. That has produced several better results so far, but still no gamepad functionality. current live example is here:

vrgo.club 

code is here:

https://gitlab.com/kylebakerio/cardboard-goban/-/blob/master/vrgo/index.html

(stuff is somewhat messy right now, first time with all this and moving at a rapid pace.)

I'm not sure if I should just give up on this component and manually build my own controls using joypad.js, I just don't understand why I get 0 response from controller and 0 output, no debug logs, nothing to work with.

Bit of a side question: is there a standard 'configure your controller' setup component anywhere in the aframe community you know of?

**Comment by kylebakerio** [comment]
This was user error, and somewhat introduced from complexities arising from trying to use NAF, and being new to aframe, NAF, and this repo (and vr and game programming in general) all at the same time. Thanks for being responsive.

When implemented properly--with a networked rig, and a networked avatar/camera, and not setting position on the avatar but ont he rig itself, everything seems to work well. +1
