### ISSUE TITLE
using dpad for non-movement.

### ISSUE THREAD

**Issue by kylebakerio** [c-frame/aframe-extras#327]
It looks like the dpad is set to be interpreted as an alternative to a joystick, basically--no built in support for using the dpad buttons for something other than movement, and letting joysticks do movement, right?

Any suggestions on best way to implement that?

Also, might be good to mention the custom events emitted in the documentation. And clean it up to not point to an article on 'current state of gamepad controls' from 2017. Open to pull requests on the readme?

**Comment by kylebakerio** [comment]
Playing with this, I'm finding that different button codes seem to trigger from the same gamepad on chrome on my desktop vs. chrome on my android; one example of that (and also something more strange), the dpad is being interpreted both as 'go left' and also firing a code this is a 'normal button'. when on desktop. (joysticks and interpreted correctly on both platforms, and while I need to debug android more, things seem to mostly be correct on desktop using this controller).

That's fine, of course, I can map inputs per-device, just curious what's going on there. Wouldn't have expected this, I thought button codes were picked by the gamepad manufacturer, so that was surprising for me.

Another quirk: arrow keys do nothing on desktop, but act as movement inputs on mobile. Any thoughts on this? I don't see any 'button press' event for the arrow keys on desktop either in this library. (They do work, and are correctly interpreted in other html5 gamepad api test pages, to be clear, and as I mentioned, are correctly recognized for movement on mobile by this library.)

There's not some debug mode that just spits out what gamepad codes it is seeing that I'm missing, right?

**Comment by n5ro** [comment]
Do you have a Windows Mixed Reality headset by chance? I was just thinking of what controller has both a dpad and a joystick and you want to assign specific functions to the dpad that are different from what you are assigning to the joystick is that right?

**Comment by n5ro** [comment]
The Aframe Thumb Controls Component allows you to independently address a thumbstick or a thumbpad. I don't know about D-Pads specifically in the sense of an xbox controller but this should work with a windows mixed reality controller. https://github.com/supermedium/superframe/tree/master/components/thumb-controls/

**Comment by n5ro** [comment]
If you need further reading the WebXR gamepad API is great documentation, a little hard to read at first, but useful.
https://immersive-web.github.io/webxr-gamepads-module/#xrinputsource-interface
and the webxr api is based on the original gamepad api which may be useful to read also
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API

**Comment by kylebakerio** [comment]
> Do you have a Windows Mixed Reality headset by chance? I was just thinking of what controller has both a dpad and a joystick and you want to assign specific functions to the dpad that are different from what you are assigning to the joystick is that right?

No, just some cheapo generic bluetooth gamepad I've had for years. Has always worked fully with native android apps, as well as with a PSP emulator I've used on desktop and android.

And yes, that's correct. I should have that option, at least. I don't recall the exact situation off the top of my head, but I will be diving back into this code soon.

**Comment by kylebakerio** [comment]
> The Aframe Thumb Controls Component allows you to independently address a thumbstick or a thumbpad. I don't know about D-Pads specifically in the sense of an xbox controller but this should work with a windows mixed reality controller. https://github.com/supermedium/superframe/tree/master/components/thumb-controls/

I might look into the thumb controls, but basically this library just seemed to have somewhat buggy input for my controller, to be clear. I got different codes in desktop usage vs mobile usage (this is not the case when I access html5 gamepad api test pages, to be clear) from this library, and some buttons seemed to send 'two codes' one one platform, while sending no codes at all on the other platform.

**Comment by kylebakerio** [comment]
> If you need further reading the WebXR gamepad API is great documentation, a little hard to read at first, but useful.
> https://immersive-web.github.io/webxr-gamepads-module/#xrinputsource-interface
> and the webxr api is based on the original gamepad api which may be useful to read also
> https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API

I've looked into that api a fair amount, but it's pretty low level, and the point of this library was to try to abstract away from going that deep if necessary. If anything, I'd rather contribute to this library if I have to go that deep so that others don't have to, and/or just move to another controller library, but this seemed to be the better aframe-compatible option...

**Comment by kylebakerio** [comment]
for future reads: This is how I ended up implementing it:

https://github.com/n5ro/aframe-extras/issues/339
