### ISSUE TITLE
animation-mixer playing specific multiple animations, but not all, at once

### ISSUE THREAD

**Issue by faychan** [c-frame/aframe-extras#328]
Following this question in issue #137 that was closed. The issue was for all animations to play at the same time and it's already solved by `using clip: '*'`, but what I need it specific multiple animations. For example: one model have 5 animations, but I want to trigger and play 2 or 3 animations at once

**Comment by mauriciomartinez-itesm** [comment]
I'm having this same issue right now, I've tried using spaces, semicolon, nothing works...

**Comment by donmccurdy** [comment]
This isn't supported currently. I'd be willing to accept a PR using [minimatch](https://www.npmjs.com/package/minimatch) syntax.

**Comment by anandbhaskaran** [comment]
I would be really happy to have this as a feature, I tested a lot of different option and just saw this open issue :)

**Comment by netgfx** [comment]
Apart from the a-frame syntax declaring multiple animations, is it supported by https://threejs.org/docs/#api/en/animation/AnimationMixer the underlying library? If it is I'll make an attempt to create a PR for it.

**Comment by donmccurdy** [comment]
AnimationMixer supports playing multiple animations at once, yes — if the goal is to support playing 2+ specific animations simultaneously with the same settings, you can do it pretty much the same way the `*` option works now. If you wanted to support triggering multiple animations at different times, with different settings, it might be better to refactor `animation-mixer` to allow multiple components on the same element, all sharing a single underlying AnimationMixer instance.

**Comment by s-light** [comment]
> f you wanted to support triggering multiple animations at different times, with different settings, it might be better to refactor `animation-mixer`

that is exactly what i need...

as this is closed - is there a way to trigger 2 animations with different settings?
i actually need one long animation to run only once and one short at the same time to repeat.

or is there at least a workaround with directly accessing the mixer?
if so is there a example out there?

**Comment by smeybi** [comment]
@s-light 
A workaround is, you can create another animation-mixer component manually, like 
AFRAME.registerComponent('animation-mixer2', ....

You find the code here:
https://github.com/n5ro/aframe-extras/blob/master/src/loaders/animation-mixer.js

With this workaround you can play 2 separate clips of the  model at the same time. 
obj.setAttribute("animation-mixer", "clip: xxx1
obj.setAttribute("animation-mixer2", "clip: yyy2

**Comment by diarmidmackenzie** [comment]
A PR for this here:
https://github.com/c-frame/aframe-extras/pull/421

(wrote this before I'd seen this issue, so didn't consider [minimatch](https://www.npmjs.com/package/minimatch), but I'm not sure what the advantage of that over regular regular expressions would be...
