### ISSUE TITLE
Aframe crashes when I press any keyboard keys or gamepad movement joystick

### ISSUE THREAD

**Issue by MrWormsy** [c-frame/aframe-extras#329]
Hi,

When I press any keyboard key or try to move into the scene with my gamepad controller it makes the scene crash.

```html
<!DOCTYPE html>
<html>
<head>
    <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script src="https://unpkg.com/aframe-event-set-component@3.0.3/dist/aframe-event-set-component.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/donmccurdy/aframe-extras@v6.1.0/dist/aframe-extras.min.js"></script>
    <script src="//cdn.rawgit.com/donmccurdy/aframe-physics-system/v4.0.1/dist/aframe-physics-system.min.js"></script>
</head>

<body>
<a-scene>
    <!-- <a-entity position="" rotation="" movement-controls=""></a-entity> -->
    <a-entity position="" rotation="" movement-controls="" gamepad-controls="" trackpad-controls="" keyboard-controls="" touch-controls=""></a-entity>
</a-scene>
</body>
</html>
```

It crashes when the "movement-controls" attribute is used (and without it I cannot move at all, only rotating the camera).

The error is : 

Uncaught TypeError: c is null
    Aframe 7
aframe-extras.min.js:1:142472

I'm using Firefox at its lastest version and it doesn't work on chromium as well.

**Comment by dirkk0** [comment]
I guess it doesn't find the camera. You need to embed the camera in the entity, like so:

      <a-entity id="rig" movement-controls="controls: checkpoint">
        <a-entity
          camera
          position="0 1.6 0"
          look-controls="pointerLockEnabled: true"
        >
        </a-entity>
      </a-entity>

**Comment by MrWormsy** [comment]
Yes you are right, thank you I wasn't aware of that !
