### ISSUE TITLE
[pathfinding] How destination work?

### ISSUE THREAD

**Issue by Turtleted21** [c-frame/aframe-extras#346]
Hello

in :
```
ctrlEl.setAttribute('nav-agent', {
        active: true,
        destination: e.detail.intersection.point
      });
```
I don't understand how destination work, what mean "intersection.point"?
 can I use a id or a position to set a destination?

Thanks

**Comment by vincentfretin** [comment]
`e.detail.intersection.point` comes from raycaster-intersected or raycaster-intersection event from the raycaster component. Look at the aframe documentation https://aframe.io/docs/1.3.0/components/raycaster.html
