### ISSUE TITLE
Console warnings by three

### ISSUE THREAD

**Issue by amichaidani** [c-frame/aframe-extras#350]
Hello,

When using extras (latest version) with a-frame 1.2.0, console is firing non-stop these warnings: "THREE.Box3: .getSize() target is now required",  "THREE.Object3D: .getWorldPosition() target is now required".

It's actually flooding the console.

Any help with that? Thanks!

**Comment by n5ro** [comment]
The big breaking change with threejs this month was the depreciation of Geometry, and the requirement that we use BufferGeometry instead. I found only one instance of THREE.Geometry in Aframe Extras and I merged a PR to fix it to THREE.BufferGeometry.

Can you test your app again to see if that made any difference.

I'm not seeing that there has been any changes to THREE.Box3, there was a change to THREE.Object3D but that was about updating the world matrix values of child objects. I'm not seeing how there could be a breaking changes with any of the threejs updates to Object3D or to Box3 going back to May of 2020.

**Comment by n5ro** [comment]
I'm still working on a fix to navmesh https://glitch.com/edit/#!/navmesh1
https://glitch.com/edit/#!/navmesh
https://glitch.com/edit/#!/navmesh2

Feel free to read the commented code in each index file for details. I am trying to replace Three.Geometry which has been deleted from threejs with BufferGeometry. I could use some help testing this and withing this code, please remix the links and try to get it working also. In the meantime use Aframe 1.1.0 with A-Frame Extras until we get this fixed.

**Comment by vincentfretin** [comment]
This particular warning was fixed by the three-pathfinding update I think. There may be others but we'll fix them when we'll verify each example with aframe master or 1.4.0. Any PR to fix a warning will be appreciated.
