### ISSUE TITLE
Pathfinding Bug

### ISSUE THREAD

**Issue by sulaemansantoso** [c-frame/aframe-extras#357]
I tried using nav-agent on CDN and it behaves weird. but when i import the nav agent directly from the file in this repo it behaves normally.

**Comment by jbolten** [comment]
maybe it is because the pull request #336  is not yet in the CDN.

**Comment by sulaemansantoso** [comment]
Yes, i think you're right. I tried it again with aframe version below 1.0 and it works flawlessly
