### ISSUE TITLE
Issue with Castles example, and general problems with navmesh

### ISSUE THREAD

**Issue by DevinBayly** [c-frame/aframe-extras#359]
Hi there,

I'm trying to use aframe-extras navmesh to constrain a camera to a landscape mesh but I'm getting the same error as when I try to load the castles example from this git repo

```
Uncaught TypeError: this.zones[t] is undefined
    getClosestNode bundle.js:8722
    getNode bundle.js:57166
    tick bundle.js:55425
    Aframe 57
```

Any idea where this is coming from?

**Comment by vincentfretin** [comment]
I don't have this error. See #388 
Please reopen if you reproduce it with the latest build.
