### ISSUE TITLE
startFrame is actually in milliseconds, not in frames

### ISSUE THREAD

**Issue by kylebakerio** [c-frame/aframe-extras#366]
makes it tricky to work with assets from my artist. He tells me start at frame 130, using a .5 timescale... that ends up being frame 14000, more or less, figured out by trial and error.

frames should be frames, or the variable should be renamed. and it shouldn't be relative to timescale--or it should be renamed or specified.

**Comment by UrjitDave** [comment]
Can you tell me how did u use the startFrame attribute of the animation-mixer component? The latest CDN link doesn't have the reference for startFrame atrribute. I have a project where I need to jump to a specific time/frame in animation of a gltf model. Any leads will be helpful, TIA.

**Comment by kylebakerio** [comment]
That's correct. You have to actually take it from master directly, not the latest CDN. I literally ended up copy/pasting the JS from the master branch itself and then making the minor tweaks to make it work.

It's not perfect, but it allows using startFrame.

**Comment by vincentfretin** [comment]
Do you want to create a PR to update documentation or adding a comment in the code here @kylebakerio ? Otherwise we can close.

**Comment by kylebakerio** [comment]
(pull request made)

**Comment by vincentfretin** [comment]
Renaming `startFrame` to `startAt` in #391
