### ISSUE TITLE
aframe 1.2.0 and navmesh

### ISSUE THREAD

**Issue by DrMicPhys** [c-frame/aframe-extras#369]
when using a simple navigation mesh

- Using aframe 1.0.4 with aframe-extras works
- Using aframe 1.2.0 with aframe-extras  does not, with the following 

  `Uncaught TypeError: THREE.Geometry is not a constructor`

When I then used a local non-min copy of aframe-extras the additional info indicates the error is 

`Uncaught TypeError: THREE.Geometry is not a constructor
         at i.loadNavMesh (aframe-extras.js:11127)`

when I used a local, non-min copy of aframe-extras

I am not a programmer, but I THINK it's the THREE.js issue mentioned in "Ocean extra nlot working on aframe 1.2.0".  That said, I have no idea what a work around might look.  There are a few other features in aframe 1.2.0 that I am trying to hold on  to (for very simple student VR projects)

**Comment by Turtleted21** [comment]
I tried this fix : https://github.com/n5ro/aframe-extras/pull/358
and can't have a navmesh with aframe 1.2.0 too.
and with aframe 1.1.0 work only on safari and firefox, not on Chrome.
Thanks

**Comment by Omegahed** [comment]
I looks like this issue was maybe fixed in `src` but never made it into `dist`?
[Fix navmeshes](https://github.com/n5ro/aframe-extras/commit/acdd9f51f352cd80d512e15d17c2c9b411d3c88d)

**Comment by vincentfretin** [comment]
The castle example is working for me on latest build, see #388

**Comment by dirkk0** [comment]
I see that @vincentfretin is working hard in this repo, first of all, thanks for that! Really appreciate it.

Then: I prepared a Glitch with a navmesh example which is working fine with 1.0.4 and not so fine with 1.3.0.
I saw that you created a new master and took the liberty to update the glitch with the current build (135d4a5):
https://glitch.com/edit/#!/dk-navmesh-02

Two observations:
a) it doesn't really work yet, but one can move a bit.
b) the console claims that Three.js was already imported, I wonder why that is?

**Comment by vincentfretin** [comment]
Thanks for the reproduction case @dirkk0 
Your navmesh looks correct when I open it in blender.
Indeed "WARNING: Multiple instances of Three.js being imported." is not normal, that may be the issue.

**Comment by vincentfretin** [comment]
I actually also have "WARNING: Multiple instances of Three.js being imported." on the castle example but it's working correctly there.

**Comment by dirkk0** [comment]
yes, I saw that too.
Also, if you uncomment the 1.0.4 in the header, the example is working. so I am pretty sure that the meshes are ok.
I am comparing the castle example to the glitch now.

**Comment by dirkk0** [comment]
got it!!

problem nr1: the arch enemy of Blender users: 'apply all tranforms'

![blender1](https://user-images.githubusercontent.com/625394/205487806-987f8b54-7c13-46d5-b937-7fb9b9daaaa2.png)

**Comment by dirkk0** [comment]
problem nr2:

navmesh doesn't like 'position' or 'scale' anymore, that's also new.

working glitch:
https://dk-navmesh-03.glitch.me/

**Comment by dirkk0** [comment]
so in a nutshell:
- don't position or scale the navmesh in A-Frame
- apply all transforms in Blender.

**Comment by vincentfretin** [comment]
Oh good catch for nr1. I'm glad you figured it out.
For nr2 it's actually a regression introduced in #358 where the applyMatrix was removed.

**Comment by vincentfretin** [comment]
Can you please help me reintroducing the applyMatrix. Can you please create a glitch example with your fixed models and add again scale and position, so I can remix it and work on a fix.

**Comment by vincentfretin** [comment]
Actually I could also work on the castle example. I see that the navmesh is 3 times bigger than the castle glb. There is a scale="3 3 3" on the castle. We should apply a position on both castle and navmesh on this example and reintroduce the applyMatrix, this way we won't reintroduce the regression in the future.

**Comment by dirkk0** [comment]
True!

If you still need an example, here it is:
https://glitch.com/edit/#!/dk-navmesh-04?path=index.html

**Comment by vincentfretin** [comment]
Thanks. I fixed it in #390. You can give the build a try in your glitch example.

**Comment by dirkk0** [comment]
I did! It's working! Great work, and thanks, Vincent!
