### ISSUE TITLE
movement-controls broken with Chrome version 97

### ISSUE THREAD

**Issue by Turtleted21** [c-frame/aframe-extras#371]
Hi,
movement-controls broken with Chrome version 97, even with aframe 1.1.0
position is not set (always 0 0 0) and mouse is locked
work on Safari, Firefox and Edge

Thanks

**Comment by eviltik** [comment]
Thank you for feedback @Turtleted21, can you provide a glitch please ? Perhaps i can help.

**Comment by Turtleted21** [comment]
I try to reproduce my bug with Glitch without succes.
In my project bug appear when I have to many entity, with less  entity it work.
It appear only with  Chrome version 97

**Comment by vincentfretin** [comment]
This seems to be an issue only on your project. I'm closing the issue. Please reopen if you reproduce your issue on a glitch example.
