### ISSUE TITLE
StartFrame not working on v6.1.1

### ISSUE THREAD

**Issue by rafelis1997** [c-frame/aframe-extras#374]
Start frame is not working on recent versions

**Comment by vincentfretin** [comment]
This is a feature that is not included in the latest release but only on master. 6.1.1 was released the 4 Sept 2020. startFrame feature was merged the 23 Mar 2021, see #337 
Be aware of #365 too.

**Comment by vincentfretin** [comment]
If you want to use the latest master with my fix, you can copy the animation-mixer component in your project (without the `modules.exports = `) https://github.com/n5ro/aframe-extras/blob/9169768f70fc9b0916a43d96cdc0d1057f18a9a1/src/loaders/animation-mixer.js it will work fine if you put `delete AFRAME.components['animation-mixer'];` just before so you register again the animation-mixer component, in case you still include aframe-extras for other things.

**Comment by vincentfretin** [comment]
You can now use the build in master
`https://cdn.jsdelivr.net/gh/n5ro/aframe-extras@8c9b13a/dist/aframe-extras.min.js`
No new release yet.
