### ISSUE TITLE
Use right stick to rotate the player in the movement controls

### ISSUE THREAD

**Issue by fangzhangmnm** [c-frame/aframe-extras#384]
Hi. I think using right stick to rotate the player in the movement controls is essential for seated VR experience

**Comment by vincentfretin** [comment]
Hi, yes, this is working on master, right?

**Comment by vincentfretin** [comment]
Be sure to use
https://cdn.jsdelivr.net/gh/n5ro/aframe-extras@8c9b13a/dist/aframe-extras.min.js

**Comment by fangzhangmnm** [comment]
> vincentfretin

Yes. it is fixed! thank you very much

BTW it's best practice to use snap rotation instead of continuous rotation.

**Comment by vincentfretin** [comment]
If you really want snap rotation, you may be interested by [aframe-blink-controls](https://github.com/jure/aframe-blink-controls) that does it by default, it's even configurable, you can disable with `snapTurn:false`. You can also contribute a PR to add it to gamepad-controls.
But you shouldn't have both movement-controls with gamepad listed and blink-controls at the same time. See [aframe-xr-boilerplate](https://github.com/AdaRoseCannon/aframe-xr-boilerplate) how it switches between the two components via a UI on your wrist, [this code](https://github.com/AdaRoseCannon/aframe-xr-boilerplate/blob/924c698c8fca5bd893801ef28b206dd6cc7f90ce/index.html#L243-L260) especially.

**Comment by dirkk0** [comment]
+1 for the aframe-xr-boilerplate. It even has a clever navigation IIRC.

**Comment by vincentfretin** [comment]
Note that gamepad-controls in this repo is a generic component. I think it can work with a XBox One or PS5 gamepad? I have none so I can't test. So by default you don't want snap turn. You want that only in VR mode.
