### ISSUE TITLE
Some features are not working

### ISSUE THREAD

**Issue by lijualivenow** [c-frame/aframe-extras#402]
with aframe 1.3.0 version some features are not working 

eg: a- ocean

**Comment by dirkk0** [comment]
This was fixed in the build:
https://github.com/n5ro/aframe-extras/pull/387
Probably not in master atm?

**Comment by lijualivenow** [comment]
here is my glitch URL https://glitch.com/edit/#!/amplified-quasar-bard

and I am using the following API(Both are working with frame 1.1.0)

```
<!--     <script src="https://cdn.jsdelivr.net/gh/donmccurdy/aframe-extras@v6.1.1/dist/aframe-extras.min.js"></script> -->
<script src="https://cdn.jsdelivr.net/gh/donmccurdy/aframe-extras/dist/aframe-extras.min.js"></script>
```

**Comment by vincentfretin** [comment]
Please specify a commit hash when using gh jsdelivr url. When you don't specify it it seems to use an old (cached?) version.
Look at the latest commit in the repo and use it in the url, so this url:
https://cdn.jsdelivr.net/gh/n5ro/aframe-extras@f4fc736/dist/aframe-extras.min.js
a-ocean is working on aframe 1.3.0 with this url.
