### ISSUE TITLE
Release to npm

### ISSUE THREAD

**Issue by 6uliver** [c-frame/aframe-extras#404]
The last release was v6.1.1 from two year ago. We need to use Github repository in our package.json to have the latest updates.

Could you release v6.2.0 to npm?

**Comment by vincentfretin** [comment]
Blocking issues to be able to create a new release:
- #389
- #395

In the meantime, please use a master build like described in the README

**Comment by 6uliver** [comment]
> Blocking issues to be able to create a new release:
> 
> * [WARNING: Multiple instances of Three.js being imported. #389](https://github.com/n5ro/aframe-extras/issues/389)
> * [Update README and examples #395](https://github.com/n5ro/aframe-extras/issues/395)
> 
> In the meantime, please use a master build like described in the README

Thank you for your quick reply! I hope these will be resolved soon.

**Comment by vincentfretin** [comment]
Any help is appreciated!

**Comment by vincentfretin** [comment]
Blocking for the 7.0.0 release :
- #380

**Comment by vincentfretin** [comment]
7.0.0 released
