### ISSUE TITLE
Transfer ownership to c-frame organization

### ISSUE THREAD

**Issue by vincentfretin** [c-frame/aframe-extras#405]
Hi @n5ro 
For the long term maintenance of the repository and to make the [c-frame](https://github.com/c-frame/) initiative more visible, can you please transfer the ownership of the repository to the c-frame organization? The transfer will keep all the PRs and issues.
I just invited you in the c-frame organization, after you accepted it, you should be able to go to Settings in this repository and at the bottom transfer ownership to c-frame organization.

**Comment by n5ro** [comment]
Hi Vincent Fretin,

I've transferred ownership of aframe-extras to the c-frame initiative.
Thank you for taking on this important project with your time!
I would have transferred aframe-physics-system at the same time but there
is a name conflict. c-frame already has a repo of the same name. How would
you like to resolve that?

Sincerely,


Micah Blumberg,

Links
github.com/n5ro
github.com/micah1
github.com/v5ma/selfawarenetworks
Featured articles, bio, and ways to connect: http://vrma.io
Main articles http://svgn.io

**Comment by vincentfretin** [comment]
Thank you!
I discussed with @diarmidmackenzie about it. For aframe-physics-system, the c-frame fork had lots issues and PRs with valuable informations, and also releases, so we can't just remove the c-frame fork and transfer yours like you just did for aframe-extras.
That's why in https://github.com/n5ro/aframe-physics-system/issues/206 I propose to just point to the new fork from now on.
Can you please add @diarmidmackenzie as maintainer on github on the repo https://github.com/n5ro/aframe-physics-system
This way he can close some issues there or transfer issues from one repo to the other. At one point we'll archive the n5ro one I guess.
