### ISSUE TITLE
I have some issues about plugins

### ISSUE THREAD

**Issue by dlxorbs** [c-frame/aframe-extras#406]
![image](https://user-images.githubusercontent.com/96194002/211189413-ad3b8c56-0328-426e-8096-87f3bdfaf8cd.png)

when i click the bulid button it doesn't work and it occured
Uncaught Error: Scene must have a bounding radius less than 500m. Reduce size, filter large objects out, or run the plugin locally.

i use aframe 1.4.0

this is my code 
https://codepen.io/afpdmbla-the-encoder/pen/yLqgbaa

**Comment by vincentfretin** [comment]
You have lots of errors in the console, first use the latest versions that are compatible with aframe 1.4.0, those are currently:
```
<script src="https://aframe.io/releases/1.4.1/aframe.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/c-frame/aframe-physics-system@v4.2.2/dist/aframe-physics-system.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/c-frame/aframe-extras@fb96ab2/dist/aframe-extras.js"></script>
```

It seems to be an issue with
https://github.com/donmccurdy/aframe-inspector-plugin-recast
not aframe-extras per se. This plugin wasn't updated for a long time. I don't know much about it myself.

**Comment by vincentfretin** [comment]
After you updated the versions, try with a simpler scene first, just primitive planes, a box on it etc. Look if it works, then add your own glb so you can pin point what model gives you an issue.

**Comment by dlxorbs** [comment]
thanks!

**Comment by dlxorbs** [comment]
can i ask one more? I have some problems about "jump-ability","kinematic-body","static-body","dynamic-body"..... Does it work in Aframe 1.4.1?
And how can I use kinematic-body & nav-mesh?
when i use both of them kinematic body cognized navmesh by square

<img width="858" alt="image" src="https://user-images.githubusercontent.com/96194002/213137851-769e7670-fbff-4e41-be9c-e8a0bc0eee26.png">

this is my Aframe Scene when i use jump-ability

https://codepen.io/afpdmbla-the-encoder/pen/yLqgbaa

**Comment by vincentfretin** [comment]
jump-ability and kinematic-body doesn't work, they have been removed from the repo.
Please use https://github.com/c-frame/aframe-physics-system instead with ammo driver for example or https://github.com/c-frame/physx
https://github.com/AdaRoseCannon/aframe-xr-boilerplate is using physx if you want an example.

**Comment by vincentfretin** [comment]
Also see the dedicated page on the wiki: https://aframe.wiki/en/#!pages/physics.md
