### ISSUE TITLE
[Animation-mixer] crossFadeDuration not accepting values less than 1

### ISSUE THREAD

**Issue by CrowtreesStudio** [c-frame/aframe-extras#429]
I've been trying to blend walking to idle animations with a short easing out and into motion. It appears the only values that it accepts is 1 and 0 but not anything less than 1 (e.g. 0.5, 0.1, etc). Is this on purpose or a 'bug'?

**Comment by vincentfretin** [comment]
`crossFadeDuration` is used for the call to `fadeIn` 
https://github.com/c-frame/aframe-extras/blob/d85de74fa99aff7c8306d13091dff82f3a4dd328/src/loaders/animation-mixer.js#L128
The unit is seconds
https://threejs.org/docs/index.html?q=animationac#api/en/animation/AnimationAction.fadeIn

Do you use aframe-extras 7.0.0?
When I use 0.2 or 0.5 in https://c-frame.github.io/aframe-extras/examples/animation-controls/ that appears to work fine.

**Comment by CrowtreesStudio** [comment]
Oh nuts. So sorry Vincent, of course I wasn't using the current version, it works as advertised now. Argh.
Carry on everyone...

Thanks Vincent

**Comment by CrowtreesStudio** [comment]
Resolved
