### ISSUE TITLE
Help with nipplejs controls

### ISSUE THREAD

**Issue by lislis** [c-frame/aframe-extras#432]
Hey there, thanks for working on aframe-extras, it's awesome!

For a tablet-only project I want to use just the nipple controls, but I can't seem to get it to work?

I set up the camera like this and as far as I can tell, that should be it, right? But nothing happens and there is also no errors in the console. 

```js
<a-entity id="rig"
          movement-controls="controls: nipple"
          nipple-controls="mode: dynamic"
          position="2 0 2">
    <a-entity camera
              position="0 1.6 0">
    </a-entity>
</a-entity>
```

I also have a simple glitch scene https://aerial-topaz-earl.glitch.me and https://glitch.com/edit/#!/aerial-topaz-earl

I'd be helpful for any pointers as to what I'm missing? Thanks in advance!

**Comment by vincentfretin** [comment]
The `look-controls` component is a required dependency for `nipple-controls`.
So
```html
          <a-entity id="rig"
                  movement-controls="controls: nipple"
                  nipple-controls="mode: dynamic"
                  position="2 0 2">
            <a-entity camera
                      look-controls
                      position="0 1.6 0">
            </a-entity>
        </a-entity>
```
Also please use latest aframe
```html
<script src="https://aframe.io/releases/1.4.2/aframe.min.js"></script>
```
