### ISSUE TITLE
Adding a Thumbnail image to Green Screen Video 

### ISSUE THREAD

**Issue by luckc** [c-frame/aframe-extras#439]
I'm almost finished with a project adding a green screen video (with sound) in AR for world placement on a flat surface.   
I have click to play and resume working fine.   
My issue is when you open up the experience the Image Plane is black, waiting for the click to start with video & audio

I have made a transparent png with "touch to play" on it including the image of first frame of video.  
How can I have it on the Image plane so it doesn't start by appearing black?  

Thank you & Happy New Year!

**Comment by vincentfretin** [comment]
Happy new year!
For support channel, you should go to Discord supermedium or Discord WebXR aframe channel, many persons can help you. You will need to give an example of your issue on a glitch to have any chance of someone helping you. Best of luck.

**Comment by luckc** [comment]
Ok thank you.  Happy New Year!

Steve Axtell, Pres & Creative Dir

AXTELL EXPRESSIONS
www.Axtell.com
