### ISSUE TITLE
Unmerge entity with "body-merger" component

### ISSUE THREAD

**Issue by Eoczi** [c-frame/aframe-extras#447]
Is there any way to unmerge an entity with the body-merger component? I tried removing the object itself from the scene but because of the dynamic-body component there is no way to remove it to the scene([issue](https://github.com/n5ro/aframe-physics-system/issues/208#issue-2312399126) regarding this)

Entity in question:
`
<a-entity id="#fruit" position="-2 6 -2" mixin="interactable" dynamic-body="shape: box; mass: 5" body-merger="body">
  <a-box mixin="cube interactable" id="#cube1" body="type: dynamic; shape: box" position="-0.5 0 0" color="red"></a-box>
  <a-box mixin="cube interactable" id="#cube2" body="type: dynamic; shape: box" position="0 0 0" color="blue"></a-box>
  <a-box mixin="cube interactable" id="#cube3" body="type: dynamic; shape: box" position="0.5 0 0" color="green"></a-box>
</a-entity>
`

**Comment by vincentfretin** [comment]
There is no body-merger component in aframe-extras. Where is this component coming from?
dynamic-body is a component from https://github.com/c-frame/aframe-physics-system
so in any case this is the wrong repository for your issue.
Look at your body-merger component implementation but probably there is no unmerge feature, if you want to unmerge, don't merge in the first place.

**Comment by Eoczi** [comment]
my bad, it was [aframe-physics-extras](https://github.com/wmurphyrd/aframe-physics-extras) not aframe-extras
