### ISSUE TITLE
My Gatsby site couldn't compile due to this package.

### ISSUE THREAD

**Issue by Yivan000** [c-frame/aframe-extras#450]
This is the error message I get when trying to compile my Gatsby site:

```
Module not found: Error: Invalid "exports" target "index.js" defined for "." in the package config [...]\node_modules\aframe-extras\package.json, targets must start with "./"
```
*(I just truncated the directory of my project with [...].)*

Upon checking, the `package.json` of this package, on line 9, reads `".": "index.js",`, which causes the error.

This package is a dependency of `react-force-graph-3d`, which I use for my Gatsby site.

I believe this is a simple fix of changing "." to "./".

**Comment by vincentfretin** [comment]
Thanks for reporting, 7.5.1 should fix your issue. '.' as a key is correct, the issue is in the value, fixed in #451
