### ISSUE TITLE
[motion-controls] No thumbstick navigation on Quest 3 after Aframe update from v1.5 to v1.6

### ISSUE THREAD

**Issue by holo05** [c-frame/aframe-extras#454]
After updating from Aframe 1.5 to Aframe 1.6, the movement via the thumbsticks on the Quest 3 no longer works (WASD movement works still fine). I don't have this problem with Aframe 1.5, version 7.2 of the aframe-extras and version 7.5.2 work perfectly. 
Is the problem known? Thanks for any hints/advice!

Quest 3 v72
Aframe 1.6
aframe-extras 7.5.2

**Comment by vincentfretin** [comment]
Last time I checked 2 weeks ago while updating https://github.com/AdaRoseCannon/aframe-xr-boilerplate aframe 1.6.0 aframe-extras 7.5.2 and I think I'm currently on Quest 3 v71 it worked well.

**Comment by holo05** [comment]
Thank you Vincent, you gave me the right direction, yes everything works fine, something was wrong with my aframe1.6 implementation, using
<script src="https://cdn.jsdelivr.net/npm/aframe@1.6.0/dist/aframe-master.min.js"></script>
solved my problem

best regards!
