### ISSUE TITLE
Investigate dealing with nested entities & local positions

### ISSUE THREAD

**Issue by donmccurdy** [c-frame/aframe-extras#46]
Body components naively assume `position` will return absolute world coordinates, which breaks if nested inside another entity with a position.

THREE.js has an API for returning world position. Could enable this by default (if there are no performance implications), or enable an option allowing it on a case-by-case basis. Might by trickier for `dynamic-body` than `static-body`.

**Comment by mikhuang** [comment]
The `syncToPhysics` part seems fairly straightforward:

```
body.quaternion.copy(this.el.object3D.getWorldQuaternion())
body.position.copy(this.el.object3D.getWorldPosition())
```

The `syncFromPhysics` part for a dynamic body seems a lot more challenging. Any chance you had another look at this? 😃

**Comment by donmccurdy** [comment]
Haven't so far, but maybe something like this for `syncFromPhysics`:

``` javascript
tmpPosition.copy(this.body.position);
tmpQuaternion.copy(this.body.quaternion);
this.el.object3D.worldToLocal(tmpPosition);
// TODO: equivalent quaternion world->local math?!?
this.el.setAttribute('position', tmpPosition);
this.el.setAttribute('quaternion', tmpQuaternion);
```

i'm sure there's a way to do the quaternion bit too.. maybe need to invert the world quaternion and then multiply them...

**Comment by donmccurdy** [comment]
@mikhuang what's your use case, by the way?

**Comment by mikhuang** [comment]
I'm making a ball throwing game where you knock cubes out of a grid of cubes. I've been trying to angle each grid of cubes around in the player in arbitrary ways. It seems most straightforward to set up each grid as a group, then to rotate the whole set instead of doing so one by one.

**Comment by donmccurdy** [comment]
Some bugs to be worked out, but a work-in-progress here: https://github.com/donmccurdy/aframe-extras/commit/e6512f7f356320c1482f4eed289c54e85755b0ff

**Comment by donmccurdy** [comment]
Can't guarantee this is really 100%, but work has been merged that seems close.

Would caution that keeping physics objects at the top level of the scene will improve performance noticeably... the world/local transformations add up quickly.
