### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by donmccurdy** [c-frame/aframe-extras#50]
Post here: http://blog.vizor.io/using-lights-and-shadows/

Suggesting directional and hemisphere lights perform (much) better than point or spot lights, when used with shadows. Also:

> "Generally, for best performance : quality ratio, it is recommended to use one directional light and either an Ambient Light or a Hemisphere Light to get a nice lighting effect with shadows."

**Comment by wizgrav** [comment]
point lights are the worst performers cause they need to render a whole cubemap

**Comment by donmccurdy** [comment]
Note to self, I should just set up a demo w/ dat.GUI and fiddle with these settings a bit.

**Comment by donmccurdy** [comment]
Default settings are more workable in current version.
