### ISSUE TITLE
Consider auto-registration when installing from NPM.

### ISSUE THREAD

**Issue by ngokevin** [c-frame/aframe-extras#67]
For convenience, less to document, less code, and consistency with browser builds, I've been setting components to auto-register (`AFRAME.registerX` directly rather than export an object or method for developers to register).

**Comment by donmccurdy** [comment]
So, I secretly dislike NPM modules with side effects. 😐  It's surprising when this fails:

```
var extras = require('aframe-extras'), // Uncaught ReferenceError: AFRAME is not defined
    aframe = require('aframe');
```

And, I'd like to give developers the option of registering components with a non-default name. I am autoregistering in the dist/ builds, though. Maybe `require('foo').registerAll()` isn't the right API. Not sure what component registration will look like a few versions down the road. Brainstorming a bit:

```
AFRAME.register([
  require('aframe-extras'),
  require('aframe-bmfont-component'),
  require('aframe-🐑 -component')
]);
```

**Comment by ngokevin** [comment]
Fair enough. Some people might also be surprised that it _doesn't_ register the components. `AFRAME.components['newname'] = AFRAME.components['oldname']` is also an option for registering under a non-default name. I think it is technically appropriate to avoid side effects which is why I had it that way before, but not worth the added code/maintenance.

A multi-register is doable, but it might not be in core since it's more of a convenience thing. It could be done in a loop and enforces a certain API.
