### ISSUE TITLE
Consider using `.updateSchema()` and put all physics body types into a single `physics` component

### ISSUE THREAD

**Issue by ngokevin** [c-frame/aframe-extras#76]
New v0.3.0 component API feature. We could have an API like:

```
<a-entity physics="body: static"></a-entity>
<a-entity physics="body: dynamic"></a-entity>
```

This would make the physics component and system 1:1 with a clearer mental model of how they relate. It'd be easier to switch the body types dynamically. It would display better on the A-Frame Inspector.

The documentation is very bare (I should expand it), but it's at https://aframe.io/docs/0.3.0/core/component.html#updateschema

**Comment by donmccurdy** [comment]
So, this can be done, but I have a concern about 1:1 component/system relationships as a hard requirement for the inspector:

A physics system is not comprised just of bodies. Even if `static-body` and `dynamic-body` were merged into a single `body` component (which is very reasonable), the physics tree is also comprised of [constraints](http://schteppe.github.io/cannon.js/docs/classes/Constraint.html) and [contact materials](http://schteppe.github.io/cannon.js/docs/classes/ContactMaterial.html). I haven't written components exposing those yet, but semantically they make sense as components. It would be difficult to merge those APIs into a single `physics` component cleanly.

Silly example:

``` html
<a-cylinder id="pole"
            body />
<a-sphere id="tetherball"
          body
          constraint="distance: 1; target: #pole; offset: 0 2 0;" />
```

![img181](https://cloud.githubusercontent.com/assets/1848368/18497247/8f29fc70-79fa-11e6-98ab-77ba5fe26064.png)

**Comment by donmccurdy** [comment]
Going to close this out; I think 1:1 parity of components and systems is a non-goal. Switching body types dynamically isn't very compatible with CannonJS either, so I don't want to give the impression that they're interchangeable.
