### ISSUE TITLE
Component jump-ability behaving incorrectly (indefinite jump)

### ISSUE THREAD

**Issue by paulocf92** [c-frame/aframe-extras#77]
While space bar is held the player will jump endlessly.

You can reproduce in any project, such as: http://drawvr.com/welcome/

**Comment by paulocf92** [comment]
The problem still persists if enableDoubleJump is true; holding space will take me to infinite.

**Comment by donmccurdy** [comment]
Replaced `enableDoubleJump: <boolean>` with `maxJumps: <number>`, which can be set to 1,2,3,... etc.
