### ISSUE TITLE
no path found on <a-tube> (extras 2.3.0/Aframe 0.3.1)

### ISSUE THREAD

**Issue by Utopiah** [c-frame/aframe-extras#80]
Getting "[a-tube] `path` property expected but not found." despite using the example from a-tube.js

extras 2.3.0
Aframe 0.3.1

**Comment by donmccurdy** [comment]
Still works for me, got a codepen?

**Comment by Utopiah** [comment]
My bad, works for me too. I tried the very same problematic codepen few hours after creating this bug report without changing any code and it worked, reliably. Apologies for not closing it earlier.

**Comment by Utopiah** [comment]
Happened again, seems like somehow if an attribute is defined before path the error pops up e.g. http://jsbin.com/vuyine/edit?html,output

**Comment by donmccurdy** [comment]
Thanks, looking into this now via https://github.com/aframevr/aframe/issues/1900

**Comment by donmccurdy** [comment]
This has been fixed upstream, in A-Frame v0.4.0.
