### ISSUE TITLE
json loader: default animation doesn't work on geometries

### ISSUE THREAD

**Issue by msj121** [c-frame/aframe-extras#83]
If you look at this model:

http://threejs.org/examples/models/skinned/marine/marine_anims_core.json

Which is used here: http://threejs.org/examples/#webgl_animation_skinning_blending

Sadly, I think the difference is that the animation there is in the "geometries" section and not in the "animations" tracks. Is there the ability to add this to the JSON loader? 

Alternatively is there a way to move the animation from geometries to animations as a workaround?

**Comment by msj121** [comment]
I did some digging in your code and the model. I think there might be a few issues with the model. The animation is saved in: "geometries.data.animations" instead of "geometries.animations".

**Comment by donmccurdy** [comment]
Huh. I've definitely noticed a lot of models don't animate, but I'd assumed there was some version mismatch  between the models and THREE.JsonLoader or THREE.ObjectLoader. If there's anything we can do here that'd be awesome, but I'm guessing we'd need PRs to THREEjs or a model conversion utility.

**Comment by msj121** [comment]
I'll try to check if there is a way to animate this new object, I think there is a lot of different json formats, but perhaps this is an old model even though its on the ThreeJS website. I really am trying to find a "humanoid" json to animate and control.

I am wondering if that type of skeletal animation might be the issue, as it might be animated differently.

**Comment by donmccurdy** [comment]
Ok, I'm closing this issue for now but I would be interested to hear what you find. Like if there's some way to tell which kinds of animation THREE.JsonLoader supports, or converters for old models.
