### ISSUE TITLE
Question: How to start build in threejs animation

### ISSUE THREAD

**Issue by fuleinist** [c-frame/aframe-extras#84]
Hi,

I am testing functions to load a threejs json file with child morphTargets pre-defined.

Just want to know if there is a way to trigger the animation after the model is loaded in the scene.

<a-entity three-model="loader:json;animation:default;src:url(models/themodels.js)" >?

I successfully loaded the model from http://threejs.org/examples/webgl_morphtargets_horse.html.

However can not find a way to trigger the animation so far.

Many Thanks

**Comment by donmccurdy** [comment]
Hi there! Thanks for this example scene. I've found some bugs in my code that are breaking morph-target animation, but will have that fixed soon.

**Comment by fuleinist** [comment]
Thanks @donmccurdy , I am actually trying to understand how this guy make it work in here:

https://musicpua.firebaseapp.com/

Looks like he managed to load all animations using your loader.

Best Regards,
Chris

**Comment by fuleinist** [comment]
Also trying to initiate animations using knight model from http://threejs.org/examples/webgl_animation_skinning_morph.html

with loader code three-model="loader:json;animation:Action;src:url(models/knight.json). The errors pop up:  "can not bind to bones as node does not have a skeleton".

I believe it's something to do with binding THREE.SkeletonHelper to the scene but so far hasn't work out the fix yet

**Comment by donmccurdy** [comment]
Looks like he made some custom changes to the component to support that (awesome work @gching!). It's a different animation format but I think we can rework `three-model` to support either one.

**Comment by donmccurdy** [comment]
Just pushed an update in e95ad2f99ea973638332d9844489e0b8077e0e5b, `horse.js` and any of the old ro.me models should work now:

``` html
<a-entity scale="0.015 0.015 0.015"
          three-model="src: url(/assets/tmp/horse.js);
                       loader: json;
                       animationDuration: 1;">
</a-entity>
```
