### ISSUE TITLE
support three JSON model with Skeletal Animation

### ISSUE THREAD

**Issue by fuleinist** [c-frame/aframe-extras#87]
After updating current json loader in [dc4d360](https://github.com/donmccurdy/aframe-extras/pull/86/commits/dc4d360865eee130f32f0b6fa1ea78f9a691cf98) I managed to load the [knight model](http://threejs.org/examples/webgl_animation_skinning_morph.html) with bones.

However the animation can not be triggered.

playAnimation fired without any error while animation didn't start. 

I am looking at how this function has been setup but could not find out why it's not started yet.

`  playAnimation: function () {
    var clip,
        data = this.data,
        animations = this.model.animations || this.model.geometry.animations || [];

```
if (!animations.length) return;

clip = data.animation === DEFAULT_ANIMATION
  ? animations[0]
  : THREE.AnimationClip.findByName(animations, data.animation);

if (!clip) {
  console.error('[three-model] Animation "%s" not found.', data.animation);
  return;
}

this.model.activeAction = this.mixer.clipAction(clip, this.model);
if (data.animationDuration) {
  this.model.activeAction.setDuration(data.animationDuration);
}
this.model.activeAction.play();
```

  },`

Source code for http://threejs.org/examples/webgl_animation_skinning_morph.html

`mesh = new THREE.SkinnedMesh( geometry, new THREE.MultiMaterial( materials ) );
...
mixer = new THREE.AnimationMixer( mesh );
bonesClip = geometry.animations[0];
...
root = rootObjects[ 0 ],

action = null,

API = {
    'play()': function play() {
    action = mixer.clipAction( clip, root );
    action.play();

},
....
`

Any thoughts anyone?

**Comment by msj121** [comment]
I have created a pull request (https://github.com/donmccurdy/aframe-extras/pull/89), this will solve both this issue, and all also https://github.com/donmccurdy/aframe-extras/pull/86...

**Comment by fuleinist** [comment]
Thanks @msj121, tested and works like a charm : )

**Comment by msj121** [comment]
My pleasure, nice to be able to commit back to this component as I really like the code and I am using it a lot so far :). As you can see I just modified your code a little bit to get it working.

**Comment by donmccurdy** [comment]
Looks like we're good here, with some more upcoming changes from msj121's #91. Thanks all!
