### ISSUE TITLE
implement gltf-model

### ISSUE THREAD

**Issue by donmccurdy** [c-frame/aframe-extras#9]
See: https://github.com/aframevr/aframe/issues/819

**Comment by donmccurdy** [comment]
https://github.com/xirvr/aframe-gltf

**Comment by msj121** [comment]
Does this mean there won't be support for the JSON loader?

**Comment by donmccurdy** [comment]
@msj121 from your other issue report I assume you found https://github.com/donmccurdy/aframe-extras/blob/master/src/loaders/three-model.js ?

**Comment by msj121** [comment]
Yes, do you think that you won't support your loader now that there is gltf?

**Comment by donmccurdy** [comment]
I'm not planning to remove `three-model`, but also not planning to create another version of xirvr's `gltf-model`.

**Comment by msj121** [comment]
Okay, great!
