### ISSUE TITLE
Module reorganization

### ISSUE THREAD

**Issue by donmccurdy** [c-frame/aframe-extras#94]
Potential changes for v3:
- [x] Move physics into a standalone repository. `aframe-physics` or `aframe-physics-system`.
  - [x] Leave `kinematic-body` behind, in `src/misc`.
  - [x] Add off-process API changes, for SW and serverside.
  - [ ] Add `constraint` and `contact-material` components.
- [x] ~~Extract animation support from `three-model`, move into a format-agnostic component. `model-animation` or `animation-mixer`.~~
- [ ] Move `universal-controls` and related components into a standalone repository. (?)

**Comment by ngokevin** [comment]
1. Consider publishing what you had for `controls` in the Extensible Controls PR to work off of.
2. One npm package per category of component. This works better since each component can have its own specific README / description / image / metadata.

**Comment by donmccurdy** [comment]
@ngokevin I'm game for that. Note that for some of those packages (controls, physics, leap motion) there is a system involved, so integration with `aframe-registry` would still be dependent on some mechanism for system installation.

**Comment by donmccurdy** [comment]
Physics: https://github.com/donmccurdy/aframe-physics-system
