### ISSUE TITLE
ocean.color not working

### ISSUE THREAD

**Issue by ngokevin** [c-frame/aframe-extras#95]
Probably an A-Frame bug? Had to use material.color.

**Comment by donmccurdy** [comment]
Likely to be https://github.com/aframevr/aframe/issues/1900

**Comment by donmccurdy** [comment]
Workaround might be

``` html
<a-entity ocean="color: #FF0000; width: 10; depth: 10; ..."><a-entity>
```

**Comment by donmccurdy** [comment]
This has been fixed upstream, in A-Frame v0.4.0.

**Comment by zcanter** [comment]
Hey great component/primitive!

Unfortunately having this color issue again. I have tried it both as a component and primitive and neither seem to allow for color adjustments.

Thank you!

**Comment by donmccurdy** [comment]
@zcanter Thanks, this should be fixed (again) now:

```html
<a-ocean width="50" depth="50" density="40" color="#44FF44"></a-ocean>
```

**Comment by zcanter** [comment]
Works great, thanks!
