### ISSUE TITLE
Include dist/ in npm publish

### ISSUE THREAD

**Issue by ngokevin** [c-frame/aframe-extras#97]
(remove the `dist`/ from npmignore) so that npmcdn works

**Comment by donmccurdy** [comment]
Is this for the registry? I think I will try to split physics into a separate repo Very Soon™. Do you still want this change, if so? It sounds like extras may need to be modularized a bit more to fit with the registry model?

**Comment by ngokevin** [comment]
Yeah, though we should just include the `dist/` anyways to enable `unpkg.com` access. That just allows me to access the file given the npm package name.

https://github.com/donmccurdy/aframe-extras/pull/98

I've created a fork in the meantime to try it out https://www.npmjs.com/package/aframe-testras :

![physics3](https://cloud.githubusercontent.com/assets/674727/19206078/610b9ac0-8c9b-11e6-85e1-5e751955207e.gif)

**Comment by donmccurdy** [comment]
Sounds good — merged and bumped to v2.5.4.
